#pragma once

/* This is autogenerated assets file, do not edit manually.
   source folder:      assets/rckid
   destination folder: librckid/assets
 */

#include <cstdint>

namespace rckid::assets {

    namespace icons {
        constexpr uint8_t gameboy[] = {
            #include "icons/gameboy.png.inc"
        }; // 1560 bytes
    } // 1560 for namespace icons

    namespace images {
        constexpr uint8_t logo_black_16[] = {
            #include "images/logo_black_16.png.inc"
        }; // 3186 bytes
        constexpr uint8_t logo_black_256[] = {
            #include "images/logo_black_256.png.inc"
        }; // 7268 bytes
        constexpr uint8_t url_qr[] = {
            #include "images/url_qr.png.inc"
        }; // 369 bytes
    } // 10823 for namespace images
} // 12383 for namespace rckid::assets
