#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  icons/icons_64 /home/peta/devel/rckid/sdk2/include/assets/icons_64.h --raw-path raw/icons_64 --namespace rckid::assets::icons_64
 */

namespace rckid::assets::icons_64 {

    // File: icons/icons_64/036-empty-box.png
    // Size: 2821
    static constexpr uint8_t empty_box[] = {
        #include "raw/icons_64/empty_box.inc.h"
    };

    // File: icons/icons_64/081-footprint.png
    // Size: 2991
    static constexpr uint8_t footprint[] = {
        #include "raw/icons_64/footprint.inc.h"
    };

} // namespace rckid::assets::icons_64
