#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  icons/icons_64 /home/peta/devel/rckid/sdk2/include/assets/icons_64.h --raw-path raw/icons_64 --namespace rckid::assets::icons_64
 */

namespace rckid::assets::icons_64 {

    // File: icons/icons_64/042-happy-face.png
    // Size: 2583
    static constexpr uint8_t happy_face[] = {
        #include "raw/icons_64/happy_face.inc.h"
    };

    // File: icons/icons_64/053-configuration.png
    // Size: 2729
    static constexpr uint8_t configuration[] = {
        #include "raw/icons_64/configuration.inc.h"
    };

    // File: icons/icons_64/036-empty-box.png
    // Size: 2821
    static constexpr uint8_t empty_box[] = {
        #include "raw/icons_64/empty_box.inc.h"
    };

    // File: icons/icons_64/052-play-button.png
    // Size: 1710
    static constexpr uint8_t play_button[] = {
        #include "raw/icons_64/play_button.inc.h"
    };

    // File: icons/icons_64/080-info.png
    // Size: 2856
    static constexpr uint8_t info[] = {
        #include "raw/icons_64/info.inc.h"
    };

    // File: icons/icons_64/022-game-controller.png
    // Size: 3058
    static constexpr uint8_t game_controller[] = {
        #include "raw/icons_64/game_controller.inc.h"
    };

    // File: icons/icons_64/015-poo.png
    // Size: 2396
    static constexpr uint8_t poo[] = {
        #include "raw/icons_64/poo.inc.h"
    };

    // File: icons/icons_64/025-folder.png
    // Size: 2621
    static constexpr uint8_t folder[] = {
        #include "raw/icons_64/folder.inc.h"
    };

    // File: icons/icons_64/002-music.png
    // Size: 2532
    static constexpr uint8_t music[] = {
        #include "raw/icons_64/music.inc.h"
    };

    // File: icons/icons_64/043-sad-face.png
    // Size: 3316
    static constexpr uint8_t sad_face[] = {
        #include "raw/icons_64/sad_face.inc.h"
    };

    // File: icons/icons_64/016-birthday-cake.png
    // Size: 1876
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons_64/birthday_cake.inc.h"
    };

    // File: icons/icons_64/081-footprint.png
    // Size: 2991
    static constexpr uint8_t footprint[] = {
        #include "raw/icons_64/footprint.inc.h"
    };

    // File: icons/icons_64/034-pen-drive.png
    // Size: 1184
    static constexpr uint8_t pen_drive[] = {
        #include "raw/icons_64/pen_drive.inc.h"
    };

    // File: icons/icons_64/037-pause.png
    // Size: 2488
    static constexpr uint8_t pause[] = {
        #include "raw/icons_64/pause.inc.h"
    };

} // namespace rckid::assets::icons_64
