#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  images /home/peta/devel/rckid/sdk2/include/assets/images.h --raw-path raw/images --namespace rckid::assets::images
 */

namespace rckid::assets::images {

    // File: images/logo.png
    // Size: 3421
    static constexpr uint8_t logo[] = {
        #include "raw/images/logo.inc.h"
    };

} // namespace rckid::assets::images
