#pragma once

/* This is autogenerated assets file, do not edit manually.
   source folder:      assets/debug
   destination folder: librckid/assets-debug
 */

#include <cstdint>

namespace rckid::assets {
    constexpr uint8_t faryra[] = {
        #include "faryra.mp3.inc"
    }; // 3230824 bytes
} // 3230824 for namespace rckid::assets
