#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets:
// generate-assets assets.def /mnt/c/devel/rckid-mk3/sdk/assets-bin rckid::assets

namespace rckid::assets {
} // namespace rckid::assets
