#include <filesystem>

#include <platform.h>
#include <platform/args.h>

#include <rckid/graphics/color.h>

#include "assets_utils.h"

/** Takes image, loads it and converts it to the raw format rom bitmap. 
 
    Usage: 

        raw-image-converter IMAGE_FILE OUTPUT_FILE [ --namespace NAMESPACE ]
 */

int main(int argc, char const * argv[]) {
    Args::Arg<std::string> inputFile{""};
    Args::Arg<std::string> outputFile{""};
    Args::Arg<std::string> ns{"namespace", "rckid::assets"};
    Args::parse(argc, argv, { inputFile, outputFile, ns});
    std::filesystem::create_directories(std::filesystem::path{outputFile.value()}.parent_path());
    // load the image
    Image img = LoadImage(inputFile.value().c_str());
    std::string name = std::filesystem::path{outputFile.value()}.stem().string();
   
    // Create output file
    std::ofstream ofile(outputFile.value());
    ofile << "#pragma once\n\n";
    ofile << "/* Autogenerated raw image." << std::endl << std::endl;
    ofile << "   Filename:    " << inputFile.value() << std::endl;
    ofile << "   Width:       " << img.width << std::endl;
    ofile << "   Height:      " << img.height << std::endl;
    ofile << "   Fomrmat:     RGB565" << std::endl;
    ofile << "   Size:        " << (img.width * img.height * sizeof(uint16_t) + 4) << " bytes" << std::endl;
    ofile << " */" << std::endl << std::endl;
    std::string indent = "";
    if (! ns.value().empty()) {
        ofile << "namespace " << ns.value() << " {" << std::endl << std::endl;
        indent = "    ";
    }
    ofile << indent << "constexpr uint8_t " << name << "[] = {";
    uint32_t i = 0;
    for (int x = img.width - 1; x >= 0; --x) {
        for (int y = 0; y < img.height; ++y) {
            if (i % 8 == 0)
                ofile << std::endl << indent << "    ";
            ::Color pixel = GetImageColor(img, x, y);
            uint16_t raw = rckid::Color::RGB(pixel.r, pixel.g, pixel.b).toRGB565();  
            ofile << (raw & 0xff) << ", " << (raw >> 8) << ", ";
            ++i;
        }
    }
    ofile << std::endl;
    ofile << indent << "    " << (img.width & 0xff) << ", " << (img.width >> 8) << ", " << std::endl;
    ofile << indent << "    " << (img.height & 0xff) << ", " << (img.height >> 8) << std::endl;
    ofile << indent << "}; // " << ns.value() << "::" << name << std::endl << std::endl;
    ofile << indent << "static_assert(" << name << "[0] != 0x89 || " << name << "[1] != 0x50, \"Will be confused with PNG\");" << std::endl;
    ofile << indent << "static_assert(" << name << "[0] != 0xff || " << name << "[1] != 0xd8, \"Will be confused with JPG\");" << std::endl;
    ofile << indent << "static_assert(" << name << "[0] != 0x71 || " << name << "[1] != 0x6f, \"Will be confused with QOI\");" << std::endl;
    

    if (! ns.value().empty())
        ofile << "} // namespace " << ns.value() << std::endl;
    UnloadImage(img);
    return EXIT_SUCCESS;
}