#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  roms/blargg-test-roms/cpu_instrs/individual tests/roms/blargg_cpu_instrs.h --raw-path raw --namespace rckid::gbcemu::rom::blargg::instrs
 */

namespace rckid::gbcemu::rom::blargg::instrs {

    // File: roms/blargg-test-roms/cpu_instrs/individual/01-special.gb
    // Size: 32768
    static constexpr uint8_t special[] = {
        #include "raw/special.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/02-interrupts.gb
    // Size: 32768
    static constexpr uint8_t interrupts[] = {
        #include "raw/interrupts.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/03-op sp,hl.gb
    // Size: 32768
    static constexpr uint8_t op_sp_hl[] = {
        #include "raw/op_sp_hl.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/04-op r,imm.gb
    // Size: 32768
    static constexpr uint8_t op_r_imm[] = {
        #include "raw/op_r_imm.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/05-op rp.gb
    // Size: 32768
    static constexpr uint8_t op_rp[] = {
        #include "raw/op_rp.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/06-ld r,r.gb
    // Size: 32768
    static constexpr uint8_t ld_r_r[] = {
        #include "raw/ld_r_r.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/07-jr,jp,call,ret,rst.gb
    // Size: 32768
    static constexpr uint8_t jr_jp_call_ret_rst[] = {
        #include "raw/jr_jp_call_ret_rst.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/08-misc instrs.gb
    // Size: 32768
    static constexpr uint8_t misc_instrs[] = {
        #include "raw/misc_instrs.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/09-op r,r.gb
    // Size: 32768
    static constexpr uint8_t op_r_r[] = {
        #include "raw/op_r_r.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/10-bit ops.gb
    // Size: 32768
    static constexpr uint8_t bit_ops[] = {
        #include "raw/bit_ops.inc.h"
    };

    // File: roms/blargg-test-roms/cpu_instrs/individual/11-op a,(hl).gb
    // Size: 32768
    static constexpr uint8_t op_a__hl_[] = {
        #include "raw/op_a__hl_.inc.h"
    };

} // namespace rckid::gbcemu::rom::blargg::instrs
