#include <cstdlib>
#include <iostream>
#include <fstream>
#include <vector>
#include <raylib.h>

#include "helpers.h"

// list of glyphs that will be part of the font
int GLYPHS[] = {
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, // space & various punctuations
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, // 0..9
    58, 59, 60, 61, 62, 63, 64, // more punctuations
    65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, // A-Z
    91, 92, 93, 94, 95, 96, // more punctuations
    97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, // a-z
    123, 124, 125, 126, // more punctiations
    0xf004, 0xf08a, //  
    0xf05a9, 0xf05aa, 0xf16c1, // 󰖩 󰖪 󱛁
    0xf244, 0xf243, 0xf242, 0xf241, 0xf240, 0xf0e7, //      
    0xf02cb, // 󰋋
    0xf1119, // 󱄙
    0xf0e08, 0xf057f, 0xf0580, 0xf057e, // 󰸈 󰕿 󰖀 󰕾
    0xf04d, 0xf04c, 0xf04b, 0xf01e, //     
    0xf0e7a, 0xf0e74, 0xf047 // 󰹺󰹴 
};

/*

    stored in column-ish format. Height is divided by four


    Glyph:
        u16 element index
        u8 advanceX
        u8 x
        u8 y
        u8 w
        u8 h / 4
        u8 free 



*/

struct Glyph {
    size_t index;
    int advanceX;
    int x;
    int y;
    int width;
    int height;
    std::vector<uint32_t> pixels;

    Glyph(size_t index, int advanceX, int x, int y, int width, int height): index{index}, advanceX{advanceX}, x{x}, y{y}, width{width}, height{height} {}
};





/** Generates font tiles from local fonts to be used on the RCKid. 
 */
int main(int argc, char * argv[]) {
    InitWindow(640, 480, "RCKid");
    SetTargetFPS(60);
    int fontSize = std::atoi(argv[2]);
    Font f = LoadFontEx(
        argv[1], 
        fontSize, 
        GLYPHS, 
        sizeof (GLYPHS) / sizeof(int)
    );
    if (!IsFontReady(f)) {
        std::cout << "ERROR: Failed to load the font" << std::endl;
        return EXIT_FAILURE;
    }
    BeginDrawing();
    DrawTextEx(f, "Hello world!" /* argv[1] */, Vector2{0,0}, fontSize, 1, WHITE);
    EndDrawing();

    std::cout << "Loaded " << f.glyphCount << " glyphs" << std::endl;
    std::cout << "Calculating glyph data..." << std::endl;
    std::vector<Glyph> glyphs;
    size_t pixelsOffset = 0;
    for (int i = 0; i < f.glyphCount; ++i) {
        GlyphInfo gi = f.glyphs[i];
        Glyph g{
            pixelsOffset,
            gi.advanceX, 
            gi.offsetX, 
            gi.offsetY,
            gi.image.width, 
            gi.image.height // will be changed to basically height / 4 
        };
        for (int x = 0; x < g.width; ++x) {
            uint32_t data = 0;
            int bytes = 0;
            for (int y = 0; y < g.height; ++y) {
                ++bytes;
                data = (data << 8) + GetImageColor(gi.image, x, y).a;
                if (bytes % 4 == 0)
                    g.pixels.push_back(data);
            }
            if (bytes % 4 != 0) {
                while (bytes % 4 != 0) {
                    data = data << 8;
                    ++bytes;
                }
                g.pixels.push_back(data);
            }
        }
        std::cout << "Glyph " << i << ": (ASCII " << GLYPHS[i] << ")" << std::endl;
        std::cout << "    aX: " << gi.advanceX << " x: " << gi.offsetX << " y: " << gi.offsetY << " w: " << gi.image.width << " h: " << gi.image.height << std::endl;
        for (int y = 0; y < g.height; ++y) {
            for (int x = 0; x < g.width; ++x) {
                uint8_t c = GetImageColor(gi.image, x, y).a;
                if (c < 64)
                    std::cout << " ";
                else if (c < 128)
                    std::cout << "\u2591";
                else if (c < 196)
                    std::cout << "\u2592";
                else 
                    std::cout << "\u2588";
            }
            std::cout << std::endl;
        }
        pixelsOffset += g.pixels.size();
        glyphs.push_back(g);
    }
    std::cout << "Glyphs array byte size: " << glyphs.size() * 8 << std::endl;
    std::cout << "Pixel data size:        " << pixelsOffset * 4 << std::endl;
    std::cout << "Writing to output file... " << std::endl;
    std::string className = baseNameOf(fs::path(argv[1]));
    std::ofstream hdr{argv[3]};
    hdr << "#pragma once" << std::endl << std::endl;
    hdr << "/* This is autogenerated font definition file. Do not edit manually." << std::endl;
    hdr << "   font file:      " << argv[1] << std::endl;
    hdr << "   font size:      " << argv[2] << std::endl;
    hdr << "   bytes (glyphs): " << glyphs.size() * 8 << std::endl;
    hdr << "   bytes (pixels): " << pixelsOffset * 4 << std::endl;
    hdr << " */" << std::endl << std::endl;
    hdr << "#include \"rckid/graphics/font.h\"" << std::endl << std::endl;
    hdr << "namespace rckid {" << std::endl;
    hdr << "    class " << className << "_" << argv[2] << " {" << std::endl;
    hdr << "    public:" << std::endl << std::endl;
    hdr << "        static constexpr unsigned size = " << argv[2] << ";" << std::endl << std::endl;
    hdr << "        static constexpr unsigned padding = " << f.glyphPadding << ";" << std::endl << std::endl;
    hdr << "        static constexpr GlyphInfo glyphs[] = {" << std::endl;
    {
        int i = 0;
        for (auto const & gi : glyphs) {
            hdr << "            GlyphInfo{" << gi.index << ", " << gi.advanceX << ", " << gi.x << ", " << gi.y << ", " << gi.width << ", " << gi.height << "}, // " << i << std::endl; 
            ++i;
        }
    }
    hdr << "        }; // glyphs" << std::endl << std::endl;
    hdr << "        static constexpr uint32_t pixels[] = {" << std::endl;
    {
        int i = 0;
        for (auto const & gi : glyphs) {
            hdr << "            ";
            for (uint32_t x : gi.pixels)
                hdr << x << ", ";
            hdr << "// " << i << std::endl;
            ++i;
        }
    }
    hdr << "        }; // pixels" << std::endl;
    hdr << "    }; // " << className << "_" << argv[1] << std::endl;
    hdr << "} // namespace rckid" << std::endl;

    /*
    while(true) {
        if (IsKeyPressed(KEY_ESCAPE))
            break;
        BeginDrawing();
        EndDrawing();
    }*/

    UnloadFont(f);
    CloseWindow();


    return EXIT_SUCCESS;
}