#include <cstdlib>
#include <iostream>
#include <fstream>
#include <vector>
#include <raylib.h>

#include "helpers.h"

// list of glyphs that will be part of the font
int GLYPHS[] = {
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, // space & various punctuations
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, // 0..9
    58, 59, 60, 61, 62, 63, 64, // more punctuations
    65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, // A-Z
    91, 92, 93, 94, 95, 96, // more punctuations
    97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, // a-z
    123, 124, 125, 126, // more punctiations
};

int SYMBOLS[] = {
    0xf004, 0xf08a, //  
    0xf05a9, 0xf05aa, 0xf16c1, // 󰖩 󰖪 󱛁
    0xf244, 0xf243, 0xf242, 0xf241, 0xf240, 0xf0e7, //      
    0xf02cb, // 󰋋
    0xf1119, // 󱄙
    0xf0e08, 0xf057f, 0xf0580, 0xf057e, // 󰸈 󰕿 󰖀 󰕾
    0xf04d, 0xf04c, 0xf04b, 0xf01e, //     
    0xf0e7a, 0xf0e74, 0xf047, // 󰹺󰹴 
    0xf07dc // 󰟜
}; 

struct Glyph {
    size_t index;
    int advanceX;
    int x;
    int y;
    int width;
    int height;
    std::vector<uint32_t> pixels;
    int codepoint;
    std::string utf8;

    Glyph(size_t index, int advanceX, int x, int y, int width, int height, int codepoint, std::string const & utf8): index{index}, advanceX{advanceX}, x{x}, y{y}, width{width}, height{height}, codepoint{codepoint}, utf8{utf8} {}
};

/** Generates font tiles from local fonts to be used on the RCKid. 
 
    Usage

        generate-font SOURCE_FONT SIZE TARGET_DIRECTORY [--symbols]

    When `--symbols` is used, the generated font will not contain the alphanumeric characters, but extra symbols. Otherwise codepoints 32 - 126 will be generated
 */
int main(int argc, char * argv[]) {
    int fontSize = std::atoi(argv[2]);
    int * glyphsToGenerate = GLYPHS;
    int numGlyphs = sizeof (GLYPHS) / sizeof(int);
    if (argc == 5 && std::string(argv[4]) == "--symbols") {
        glyphsToGenerate = SYMBOLS;
        numGlyphs = sizeof (SYMBOLS) / sizeof(int);
    }
    std::ifstream input(argv[1], std::ios::binary);
    std::vector<unsigned char> bytes(
         (std::istreambuf_iterator<char>(input)),
         (std::istreambuf_iterator<char>()));
    input.close();   
    GlyphInfo * glyphInfos = LoadFontData(bytes.data(), bytes.size(), fontSize, glyphsToGenerate, numGlyphs, FONT_DEFAULT);

    std::cout << "Loaded " << numGlyphs << " glyphs" << std::endl;
    std::cout << "Calculating glyph data..." << std::endl;
    std::vector<Glyph> glyphs;
    size_t pixelsOffset = 0;
    for (int i = 0; i < numGlyphs; ++i) {
        GlyphInfo gi = glyphInfos[i];
        std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> converter;
        std::string utf8 = converter.to_bytes(glyphsToGenerate[i]);
        Glyph g{
            pixelsOffset,
            gi.advanceX, 
            gi.offsetX, 
            gi.offsetY,
            gi.image.width, 
            gi.image.height,
            glyphsToGenerate[i],
            utf8

        };
        for (int x = 0; x < g.width; ++x) {
            uint32_t data = 0;
            int bits = 0;
            for (int y = 0; y < g.height; ++y) {
                // get the value rounded to bpps
                int c = GetImageColor(gi.image, x, y).r;
                c = (std::min(255, (c + 32)) >> 6) & 3;
                data = (data << 2);
                data = data | c;
                bits += 2;
                if (bits == 32) {
                    g.pixels.push_back(data);
                    data = 0;
                    bits = 0;
                }
            }
            if (bits != 0) {
                data = data << (32 - bits);
                g.pixels.push_back(data);
            }
        }
        pixelsOffset += g.pixels.size();
        glyphs.push_back(g);
    }
    std::cout << "Glyphs array byte size: " << glyphs.size() * 8 << std::endl;
    std::cout << "Pixel data size:        " << pixelsOffset * 4 << std::endl;
    std::cout << "Writing to output file... " << std::endl;
    std::string className = baseNameOf(fs::path(argv[1])) + "_" + argv[2];
    std::ofstream hdr{std::string(argv[3]) + "/" + className + ".h"};
    hdr << "#pragma once" << std::endl << std::endl;
    hdr << "/* This is autogenerated font definition file. Do not edit manually." << std::endl;
    hdr << "   font file:      " << argv[1] << std::endl;
    hdr << "   font size:      " << fontSize << std::endl;
    hdr << "   bytes (glyphs): " << glyphs.size() * 8 << std::endl;
    hdr << "   bytes (pixels): " << pixelsOffset * 4 << std::endl;
    hdr << " */" << std::endl << std::endl;
    hdr << "#include \"rckid/graphics/font.h\"" << std::endl << std::endl;
    hdr << "namespace rckid {" << std::endl;
    hdr << "    class " << className << "_Data {" << std::endl;
    hdr << "    public:" << std::endl << std::endl;
    hdr << "        static constexpr int size = " << argv[2] << ";" << std::endl << std::endl;
    hdr << "        static constexpr GlyphInfo glyphs[] = {" << std::endl;
    {
        int i = 0;
        for (auto const & gi : glyphs) {
            hdr << "            GlyphInfo{" << gi.index << ", " << gi.advanceX << ", " << gi.x << ", " << gi.y << ", " << gi.width << ", " << gi.height << "}, // " << i << " (codepoint: " << gi.codepoint << ", " << gi.utf8 << ")" << std::endl; 
            for (int y = 0; y < gi.height; ++y) {
                hdr << "            // ";
                for (int x = 0; x < gi.width; ++x) {
                    uint8_t c = GetImageColor(glyphInfos[i].image, x, y).r;
                    if (c < 64)
                        hdr << " ";
                    else if (c < 128)
                        hdr << "\u2591";
                    else if (c < 196)
                        hdr << "\u2592";
                    else 
                        hdr << "\u2588";
                }
                hdr << std::endl;
            }
            hdr << std::endl;
            ++i;
        }
    }
    hdr << "        }; // glyphs" << std::endl << std::endl;
    hdr << "        static constexpr uint32_t pixels[] = {" << std::endl;
    {
        int i = 0;
        for (auto const & gi : glyphs) {
            hdr << "            // " << i << " (codepoint: " << gi.codepoint << ", " << gi.utf8 << ")" << std::endl;
            hdr << "            ";
            for (uint32_t x : gi.pixels)
                hdr << x << ",";
            hdr << std::endl;    
            ++i;
        }
    }
    hdr << "        }; // pixels" << std::endl;
    hdr << "    }; // " << className << "_" << argv[1] << std::endl << std::endl;
    hdr << "    constexpr Font " << className << " = Font::fromROM<" << className << "_Data>();" << std::endl << std::endl;
    hdr << "} // namespace rckid" << std::endl;

    UnloadFontData(glyphInfos, numGlyphs);

    return EXIT_SUCCESS;
}