#include <cstdio>
#include <iostream>
#include <fstream>
#include <ios>
#include <vector>
#include <filesystem>

using namespace std::filesystem;

/** Generates single asset. Takes the src file and creates from it an inc file
 * 
 */
void generateAsset(path src, path dst) {
    dst += ".inc";
    std::cout << "  converting " << src << " to " << dst << std::endl;
    std::ifstream input(src, std::ios::binary);
    std::vector<char> bytes(
         (std::istreambuf_iterator<char>(input)),
         (std::istreambuf_iterator<char>()));
    input.close();   
    std::ofstream output(dst);
    output << "// RCKid includable asset, generated by generate-assets" << std::endl;
    output << "// Do not modify this file" << std::endl;
    int i = 0; 
    for (char c : bytes) {
        unsigned x = *reinterpret_cast<unsigned char*>(& c);
        output << x << ",";
        if (++i % 16 == 0)
            output << std::endl;
    }
    output.close();
}

void generateAssetsIn(path src, path dst) {
    std::cout << "Analyzing folder " << src << std::endl;
    create_directories(dst);
    for (auto const & entry : directory_iterator{src}) {
        path dstPath = dst / entry.path().filename();
        if (entry.is_directory()) 
            generateAssetsIn(entry.path(), dstPath);
        else if (entry.is_regular_file()) 
            generateAsset(entry.path(), dstPath);
    }
}



/** Generates includable data from binary assets. 

    Usage:

        generate-assets SRC_DIR DEST_DIR 
 */
int main(int argc, char * argv[]) {
    path src = argv[1];
    path dst = argv[2];
    generateAssetsIn(src, dst);
    return EXIT_SUCCESS;
}