#include <cstdio>
#include <iostream>
#include <fstream>
#include <ios>
#include <vector>
#include <filesystem>
#include <iomanip>
#include <algorithm>

#include "helpers.h"

std::string toIdentifier(std::string from) {
    std::replace(from.begin(), from.end(), '-', '_');
    size_t i = 0;
    while (i < from.size() && ((from[i] >= '0' && from[i] <= '9') || from[i] == '_'))
        ++i;
    return from.substr(i);
}

/** Generates single asset. Takes the src file and creates from it an inc file
 * 
 */
size_t generateAsset(fs::path src, fs::path dst) {
    std::cout << "  converting " << src << " to " << dst << std::endl;
    std::ifstream input(src, std::ios::binary);
    std::vector<char> bytes(
         (std::istreambuf_iterator<char>(input)),
         (std::istreambuf_iterator<char>()));
    input.close();   
    std::ofstream output(dst);
    output << "// RCKid includable asset, generated by generate-assets" << std::endl;
    output << "// Do not modify this file" << std::endl;
    size_t i = 0; 
    for (char c : bytes) {
        unsigned x = *reinterpret_cast<unsigned char*>(& c);
        output << x << ",";
        if (++i % 16 == 0)
            output << std::endl;
    }
    output.close();
    return i;
}

size_t  generateAssetsIn(fs::path src, fs::path dst, fs::path dstRoot, std::ofstream & hdr, int indent = 4) {
    std::cout << "Analyzing folder " << src << std::endl;
    // only delete non root dirs since we allow non-generated asset directories
    if (dst != dstRoot) {
        fs::remove_all(dst);
        fs::create_directories(dst);
    }
    size_t totalBytes = 0;
    for (auto const & entry : fs::directory_iterator{src}) {
        fs::path dstPath = dst / entry.path().filename();
        if (entry.is_directory()) { 
            hdr << std::endl;
            hdr << std::setw(indent) << " " << "namespace " << baseNameOf(entry.path()) << " {" << std::endl;
            size_t bytes = generateAssetsIn(entry.path(), dstPath, dstRoot, hdr, indent + 4);
            totalBytes += bytes;
            hdr << std::setw(indent) << " " << "} // " << bytes << " for namespace " << baseNameOf(entry.path()) << std::endl;
        } else if (entry.is_regular_file()) {
            dstPath += ".inc";
            size_t bytes = generateAsset(entry.path(), dstPath);
            hdr << std::setw(indent) << " " << "constexpr uint8_t " << toIdentifier(baseNameOf(dstPath)) << "[] = {" << std::endl;
            hdr << std::setw(indent) << " " << "    #include \"" << std::string{fs::relative(dstPath, dstRoot)} << "\"" << std::endl;
            hdr << std::setw(indent) << " " << "}; // " << bytes << " bytes" << std::endl;
            totalBytes += bytes;
        }
    }
    return totalBytes;
}



/** Generates includable data from binary assets. 

    Usage:

        generate-assets SRC_DIR DEST_DIR
 */
int main(int argc, char * argv[]) {
    fs::path src = argv[1];
    fs::path dst = argv[2];
    std::ofstream hdr{dst / "all.h"};
    hdr << "#pragma once" << std::endl << std::endl;
    hdr << "/* This is autogenerated assets file, do not edit manually." << std::endl;
    hdr << "   source folder:      " << std::string{src} << std::endl;
    hdr << "   destination folder: " << std::string{dst} << std::endl;
    hdr << " */" << std::endl << std::endl;
    hdr << "#include <cstdint>" << std::endl << std::endl;
    hdr << "namespace rckid::assets {" << std::endl;
    size_t totalBytes = generateAssetsIn(src, dst, dst, hdr);
    hdr << "} // " << totalBytes << " for namespace rckid::assets" << std::endl;
    std::cout << totalBytes << " total bytes generated" << std::endl;
    return EXIT_SUCCESS;
}