#include <cstdio>
#include <iostream>
#include <cmath>
#include <fstream>

/** Generates interpolation tables. 

    Usage:

        generate-interp-tables size output_file
 
*/
int main(int argc, char * argv[]) {
    int size = std::atoi(argv[1]);
    std::ofstream f{argv[2]};
    f << "#pragma once" << std::endl << std::endl;
    f << "/* This is autogenerated interpolation table. Do not edit manually." << std::endl;
    f << " */" << std::endl << std::endl;
    f << "#include <cstdint>" << std::endl << std::endl;
    f << "namespace rckid {" << std::endl << std::endl;
    f << "    /** One quarter of sine wave, from 0 to max within uint16_t." << std::endl;
    f << "     */" << std::endl;
    f << "    constexpr uint16_t SineTable[] = {";
    for (unsigned i = 0; i < size; ++i) {
        if (i % 8 == 0) {
            f << std::endl;
            f << "        ";
        }
        f << static_cast<unsigned>(sin(i / (size * 2.0) * M_PI) * 65535) << ", ";  
    }
    f << std::endl << "    };" << std::endl << std::endl;
    f << "} // namespace rckid" << std::endl;
    return EXIT_SUCCESS;
}