#pragma once

/* This is autogenerated interpolation table. Do not edit manually.
 */

#include <cstdint>

namespace rckid {

    /** One quarter of sine wave, from 0 to max within uint16_t.
     */
    constexpr uint16_t SineTable[] = {
        #include "easing_sine.inc.h"
    };

} // namespace rckid
