#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  assets/icons/64 rckid/assets/icons_64.h --raw-path raw/icons64 --namespace rckid::assets::icons_64
 */

namespace rckid::assets::icons_64 {

    // File: assets/icons/64/040-hourglass.png
    // Size: 2252
    static constexpr uint8_t hourglass[] = {
        #include "raw/icons64/hourglass.inc.h"
    };

    // File: assets/icons/64/004-film-slate.png
    // Size: 2563
    static constexpr uint8_t film_slate[] = {
        #include "raw/icons64/film_slate.inc.h"
    };

    // File: assets/icons/64/074-up-arrow.png
    // Size: 1384
    static constexpr uint8_t up_arrow[] = {
        #include "raw/icons64/up_arrow.inc.h"
    };

    // File: assets/icons/64/062-fireworks.png
    // Size: 2848
    static constexpr uint8_t fireworks[] = {
        #include "raw/icons64/fireworks.inc.h"
    };

    // File: assets/icons/64/042-happy-face.png
    // Size: 2583
    static constexpr uint8_t happy_face[] = {
        #include "raw/icons64/happy_face.inc.h"
    };

    // File: assets/icons/64/054-music-wave.png
    // Size: 2937
    static constexpr uint8_t music_wave[] = {
        #include "raw/icons64/music_wave.inc.h"
    };

    // File: assets/icons/64/066-rainbow.png
    // Size: 2430
    static constexpr uint8_t rainbow[] = {
        #include "raw/icons64/rainbow.inc.h"
    };

    // File: assets/icons/64/064-color-picker.png
    // Size: 2650
    static constexpr uint8_t color_picker[] = {
        #include "raw/icons64/color_picker.inc.h"
    };

    // File: assets/icons/64/071-family.png
    // Size: 4909
    static constexpr uint8_t family[] = {
        #include "raw/icons64/family.inc.h"
    };

    // File: assets/icons/64/048-sleeping.png
    // Size: 2735
    static constexpr uint8_t sleeping[] = {
        #include "raw/icons64/sleeping.inc.h"
    };

    // File: assets/icons/64/061-santa-claus.png
    // Size: 3927
    static constexpr uint8_t santa_claus[] = {
        #include "raw/icons64/santa_claus.inc.h"
    };

    // File: assets/icons/64/007-brightness.png
    // Size: 1908
    static constexpr uint8_t brightness[] = {
        #include "raw/icons64/brightness.inc.h"
    };

    // File: assets/icons/64/038-money-bag.png
    // Size: 2500
    static constexpr uint8_t money_bag[] = {
        #include "raw/icons64/money_bag.inc.h"
    };

    // File: assets/icons/64/053-configuration.png
    // Size: 2729
    static constexpr uint8_t configuration[] = {
        #include "raw/icons64/configuration.inc.h"
    };

    // File: assets/icons/64/017-presents.png
    // Size: 3299
    static constexpr uint8_t presents[] = {
        #include "raw/icons64/presents.inc.h"
    };

    // File: assets/icons/64/014-signal.png
    // Size: 3456
    static constexpr uint8_t signal[] = {
        #include "raw/icons64/signal.inc.h"
    };

    // File: assets/icons/64/023-chat.png
    // Size: 2658
    static constexpr uint8_t chat[] = {
        #include "raw/icons64/chat.inc.h"
    };

    // File: assets/icons/64/046-bookmark.png
    // Size: 1473
    static constexpr uint8_t bookmark[] = {
        #include "raw/icons64/bookmark.inc.h"
    };

    // File: assets/icons/64/050-ladybug.png
    // Size: 2701
    static constexpr uint8_t ladybug[] = {
        #include "raw/icons64/ladybug.inc.h"
    };

    // File: assets/icons/64/036-empty-box.png
    // Size: 2821
    static constexpr uint8_t empty_box[] = {
        #include "raw/icons64/empty_box.inc.h"
    };

    // File: assets/icons/64/029-notes.png
    // Size: 2624
    static constexpr uint8_t notes[] = {
        #include "raw/icons64/notes.inc.h"
    };

    // File: assets/icons/64/079-pocket-knife.png
    // Size: 1916
    static constexpr uint8_t pocket_knife[] = {
        #include "raw/icons64/pocket_knife.inc.h"
    };

    // File: assets/icons/64/013-wifi.png
    // Size: 2244
    static constexpr uint8_t wifi[] = {
        #include "raw/icons64/wifi.inc.h"
    };

    // File: assets/icons/64/077-microchip.png
    // Size: 3982
    static constexpr uint8_t microchip[] = {
        #include "raw/icons64/microchip.inc.h"
    };

    // File: assets/icons/64/001-rc-car.png
    // Size: 2955
    static constexpr uint8_t rc_car[] = {
        #include "raw/icons64/rc_car.inc.h"
    };

    // File: assets/icons/64/058-email.png
    // Size: 1060
    static constexpr uint8_t email[] = {
        #include "raw/icons64/email.inc.h"
    };

    // File: assets/icons/64/041-applications.png
    // Size: 2046
    static constexpr uint8_t applications[] = {
        #include "raw/icons64/applications.inc.h"
    };

    // File: assets/icons/64/063-star.png
    // Size: 2267
    static constexpr uint8_t star[] = {
        #include "raw/icons64/star.inc.h"
    };

    // File: assets/icons/64/052-play-button.png
    // Size: 1710
    static constexpr uint8_t play_button[] = {
        #include "raw/icons64/play_button.inc.h"
    };

    // File: assets/icons/64/073-vibration.png
    // Size: 1508
    static constexpr uint8_t vibration[] = {
        #include "raw/icons64/vibration.inc.h"
    };

    // File: assets/icons/64/080-info.png
    // Size: 2856
    static constexpr uint8_t info[] = {
        #include "raw/icons64/info.inc.h"
    };

    // File: assets/icons/64/060-exchange.png
    // Size: 2357
    static constexpr uint8_t exchange[] = {
        #include "raw/icons64/exchange.inc.h"
    };

    // File: assets/icons/64/056-phone.png
    // Size: 2145
    static constexpr uint8_t phone[] = {
        #include "raw/icons64/phone.inc.h"
    };

    // File: assets/icons/64/049-read.png
    // Size: 3609
    static constexpr uint8_t read[] = {
        #include "raw/icons64/read.inc.h"
    };

    // File: assets/icons/64/028-tetris.png
    // Size: 667
    static constexpr uint8_t tetris[] = {
        #include "raw/icons64/tetris.inc.h"
    };

    // File: assets/icons/64/068-easter.png
    // Size: 3725
    static constexpr uint8_t easter[] = {
        #include "raw/icons64/easter.inc.h"
    };

    // File: assets/icons/64/018-heart.png
    // Size: 1981
    static constexpr uint8_t heart[] = {
        #include "raw/icons64/heart.inc.h"
    };

    // File: assets/icons/64/022-game-controller.png
    // Size: 3058
    static constexpr uint8_t game_controller[] = {
        #include "raw/icons64/game_controller.inc.h"
    };

    // File: assets/icons/64/015-poo.png
    // Size: 2396
    static constexpr uint8_t poo[] = {
        #include "raw/icons64/poo.inc.h"
    };

    // File: assets/icons/64/025-folder.png
    // Size: 2621
    static constexpr uint8_t folder[] = {
        #include "raw/icons64/folder.inc.h"
    };

    // File: assets/icons/64/020-playlist.png
    // Size: 1291
    static constexpr uint8_t playlist[] = {
        #include "raw/icons64/playlist.inc.h"
    };

    // File: assets/icons/64/055-radio-cassette.png
    // Size: 2110
    static constexpr uint8_t radio_cassette[] = {
        #include "raw/icons64/radio_cassette.inc.h"
    };

    // File: assets/icons/64/070-idea.png
    // Size: 1682
    static constexpr uint8_t idea[] = {
        #include "raw/icons64/idea.inc.h"
    };

    // File: assets/icons/64/027-paint-palette.png
    // Size: 3267
    static constexpr uint8_t paint_palette[] = {
        #include "raw/icons64/paint_palette.inc.h"
    };

    // File: assets/icons/64/059-shuffle.png
    // Size: 2839
    static constexpr uint8_t shuffle[] = {
        #include "raw/icons64/shuffle.inc.h"
    };

    // File: assets/icons/64/026-music-2.png
    // Size: 3152
    static constexpr uint8_t music_2[] = {
        #include "raw/icons64/music_2.inc.h"
    };

    // File: assets/icons/64/002-music.png
    // Size: 2532
    static constexpr uint8_t music[] = {
        #include "raw/icons64/music.inc.h"
    };

    // File: assets/icons/64/030-music-note.png
    // Size: 2091
    static constexpr uint8_t music_note[] = {
        #include "raw/icons64/music_note.inc.h"
    };

    // File: assets/icons/64/078-numpad.png
    // Size: 2355
    static constexpr uint8_t numpad[] = {
        #include "raw/icons64/numpad.inc.h"
    };

    // File: assets/icons/64/076-down-arrow.png
    // Size: 1456
    static constexpr uint8_t down_arrow[] = {
        #include "raw/icons64/down_arrow.inc.h"
    };

    // File: assets/icons/64/043-sad-face.png
    // Size: 3316
    static constexpr uint8_t sad_face[] = {
        #include "raw/icons64/sad_face.inc.h"
    };

    // File: assets/icons/64/031-boy.png
    // Size: 3508
    static constexpr uint8_t boy[] = {
        #include "raw/icons64/boy.inc.h"
    };

    // File: assets/icons/64/047-appointment-book.png
    // Size: 1770
    static constexpr uint8_t appointment_book[] = {
        #include "raw/icons64/appointment_book.inc.h"
    };

    // File: assets/icons/64/012-alarm-clock.png
    // Size: 4855
    static constexpr uint8_t alarm_clock[] = {
        #include "raw/icons64/alarm_clock.inc.h"
    };

    // File: assets/icons/64/035-gameboy.png
    // Size: 1560
    static constexpr uint8_t gameboy[] = {
        #include "raw/icons64/gameboy.inc.h"
    };

    // File: assets/icons/64/065-light.png
    // Size: 3247
    static constexpr uint8_t light[] = {
        #include "raw/icons64/light.inc.h"
    };

    // File: assets/icons/64/008-high-volume.png
    // Size: 2396
    static constexpr uint8_t high_volume[] = {
        #include "raw/icons64/high_volume.inc.h"
    };

    // File: assets/icons/64/069-lock.png
    // Size: 1524
    static constexpr uint8_t lock[] = {
        #include "raw/icons64/lock.inc.h"
    };

    // File: assets/icons/64/009-power-off.png
    // Size: 3139
    static constexpr uint8_t power_off[] = {
        #include "raw/icons64/power_off.inc.h"
    };

    // File: assets/icons/64/033-screenshot.png
    // Size: 2072
    static constexpr uint8_t screenshot[] = {
        #include "raw/icons64/screenshot.inc.h"
    };

    // File: assets/icons/64/016-birthday-cake.png
    // Size: 1876
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons64/birthday_cake.inc.h"
    };

    // File: assets/icons/64/010-airplane-mode.png
    // Size: 1592
    static constexpr uint8_t airplane_mode[] = {
        #include "raw/icons64/airplane_mode.inc.h"
    };

    // File: assets/icons/64/081-footprint.png
    // Size: 2991
    static constexpr uint8_t footprint[] = {
        #include "raw/icons64/footprint.inc.h"
    };

    // File: assets/icons/64/021-chronometer.png
    // Size: 3077
    static constexpr uint8_t chronometer[] = {
        #include "raw/icons64/chronometer.inc.h"
    };

    // File: assets/icons/64/006-baby-monitor.png
    // Size: 2168
    static constexpr uint8_t baby_monitor[] = {
        #include "raw/icons64/baby_monitor.inc.h"
    };

    // File: assets/icons/64/005-baby-crib.png
    // Size: 3068
    static constexpr uint8_t baby_crib[] = {
        #include "raw/icons64/baby_crib.inc.h"
    };

    // File: assets/icons/64/039-medal.png
    // Size: 2513
    static constexpr uint8_t medal[] = {
        #include "raw/icons64/medal.inc.h"
    };

    // File: assets/icons/64/075-brightness-1.png
    // Size: 1359
    static constexpr uint8_t brightness_1[] = {
        #include "raw/icons64/brightness_1.inc.h"
    };

    // File: assets/icons/64/019-music-1.png
    // Size: 2182
    static constexpr uint8_t music_1[] = {
        #include "raw/icons64/music_1.inc.h"
    };

    // File: assets/icons/64/057-house.png
    // Size: 3067
    static constexpr uint8_t house[] = {
        #include "raw/icons64/house.inc.h"
    };

    // File: assets/icons/64/067-turn-off.png
    // Size: 1708
    static constexpr uint8_t turn_off[] = {
        #include "raw/icons64/turn_off.inc.h"
    };

    // File: assets/icons/64/044-picture.png
    // Size: 3964
    static constexpr uint8_t picture[] = {
        #include "raw/icons64/picture.inc.h"
    };

    // File: assets/icons/64/034-pen-drive.png
    // Size: 1184
    static constexpr uint8_t pen_drive[] = {
        #include "raw/icons64/pen_drive.inc.h"
    };

    // File: assets/icons/64/024-microphone.png
    // Size: 3240
    static constexpr uint8_t microphone[] = {
        #include "raw/icons64/microphone.inc.h"
    };

    // File: assets/icons/64/051-product.png
    // Size: 2004
    static constexpr uint8_t product[] = {
        #include "raw/icons64/product.inc.h"
    };

    // File: assets/icons/64/072-piggy-bank.png
    // Size: 2579
    static constexpr uint8_t piggy_bank[] = {
        #include "raw/icons64/piggy_bank.inc.h"
    };

    // File: assets/icons/64/037-pause.png
    // Size: 2488
    static constexpr uint8_t pause[] = {
        #include "raw/icons64/pause.inc.h"
    };

    // File: assets/icons/64/032-girl.png
    // Size: 4017
    static constexpr uint8_t girl[] = {
        #include "raw/icons64/girl.inc.h"
    };

    // File: assets/icons/64/011-settings.png
    // Size: 2825
    static constexpr uint8_t settings[] = {
        #include "raw/icons64/settings.inc.h"
    };

    // File: assets/icons/64/003-flashlight.png
    // Size: 2323
    static constexpr uint8_t flashlight[] = {
        #include "raw/icons64/flashlight.inc.h"
    };

    // File: assets/icons/64/045-logout.png
    // Size: 1420
    static constexpr uint8_t logout[] = {
        #include "raw/icons64/logout.inc.h"
    };

} // namespace rckid::assets::icons_64
