#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: icons64
namespace rckid::assets::icons64{

    // File: 001-game-controller.png
    // Size: 3058
    static constexpr uint8_t game_controller[] = {
        #include "raw/icons64/001-game-controller.png.h"
    };

    // File: 002-rc-car.png
    // Size: 2955
    static constexpr uint8_t rc_car[] = {
        #include "raw/icons64/002-rc-car.png.h"
    };

    // File: 003-music.png
    // Size: 2532
    static constexpr uint8_t music[] = {
        #include "raw/icons64/003-music.png.h"
    };

    // File: 004-flashlight.png
    // Size: 2323
    static constexpr uint8_t flashlight[] = {
        #include "raw/icons64/004-flashlight.png.h"
    };

    // File: 005-film-slate.png
    // Size: 2563
    static constexpr uint8_t film_slate[] = {
        #include "raw/icons64/005-film-slate.png.h"
    };

    // File: 006-baby-crib.png
    // Size: 3068
    static constexpr uint8_t baby_crib[] = {
        #include "raw/icons64/006-baby-crib.png.h"
    };

    // File: 007-baby-monitor.png
    // Size: 2168
    static constexpr uint8_t baby_monitor[] = {
        #include "raw/icons64/007-baby-monitor.png.h"
    };

    // File: 008-unicorn.png
    // Size: 5834
    static constexpr uint8_t unicorn[] = {
        #include "raw/icons64/008-unicorn.png.h"
    };

    // File: 009-brightness.png
    // Size: 1908
    static constexpr uint8_t brightness[] = {
        #include "raw/icons64/009-brightness.png.h"
    };

    // File: 010-high-volume.png
    // Size: 2396
    static constexpr uint8_t high_volume[] = {
        #include "raw/icons64/010-high-volume.png.h"
    };

    // File: 011-power-off.png
    // Size: 3139
    static constexpr uint8_t power_off[] = {
        #include "raw/icons64/011-power-off.png.h"
    };

    // File: 012-airplane-mode.png
    // Size: 1592
    static constexpr uint8_t airplane_mode[] = {
        #include "raw/icons64/012-airplane-mode.png.h"
    };

    // File: 013-settings.png
    // Size: 2825
    static constexpr uint8_t settings[] = {
        #include "raw/icons64/013-settings.png.h"
    };

    // File: 014-info.png
    // Size: 1707
    static constexpr uint8_t info[] = {
        #include "raw/icons64/014-info.png.h"
    };

    // File: 015-alarm-clock.png
    // Size: 4855
    static constexpr uint8_t alarm_clock[] = {
        #include "raw/icons64/015-alarm-clock.png.h"
    };

    // File: 016-wifi.png
    // Size: 2244
    static constexpr uint8_t wifi[] = {
        #include "raw/icons64/016-wifi.png.h"
    };

    // File: 017-signal.png
    // Size: 3456
    static constexpr uint8_t signal[] = {
        #include "raw/icons64/017-signal.png.h"
    };

    // File: 018-cancel.png
    // Size: 2359
    static constexpr uint8_t cancel[] = {
        #include "raw/icons64/018-cancel.png.h"
    };

    // File: 019-sad.png
    // Size: 1699
    static constexpr uint8_t sad[] = {
        #include "raw/icons64/019-sad.png.h"
    };

    // File: 020-poo.png
    // Size: 2396
    static constexpr uint8_t poo[] = {
        #include "raw/icons64/020-poo.png.h"
    };

    // File: 021-birthday-cake.png
    // Size: 1876
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons64/021-birthday-cake.png.h"
    };

    // File: 022-presents.png
    // Size: 3299
    static constexpr uint8_t presents[] = {
        #include "raw/icons64/022-presents.png.h"
    };

    // File: 023-easter.png
    // Size: 3725
    static constexpr uint8_t easter[] = {
        #include "raw/icons64/023-easter.png.h"
    };

    // File: 024-santa-hat.png
    // Size: 2516
    static constexpr uint8_t santa_hat[] = {
        #include "raw/icons64/024-santa-hat.png.h"
    };

    // File: 025-heart.png
    // Size: 1981
    static constexpr uint8_t heart[] = {
        #include "raw/icons64/025-heart.png.h"
    };

    // File: 026-magic-wand.png
    // Size: 2836
    static constexpr uint8_t magic_wand[] = {
        #include "raw/icons64/026-magic-wand.png.h"
    };

    // File: 027-fairy.png
    // Size: 3027
    static constexpr uint8_t fairy[] = {
        #include "raw/icons64/027-fairy.png.h"
    };

    // File: 028-unicorn-1.png
    // Size: 3341
    static constexpr uint8_t unicorn_1[] = {
        #include "raw/icons64/028-unicorn-1.png.h"
    };

    // File: 029-book.png
    // Size: 3735
    static constexpr uint8_t book[] = {
        #include "raw/icons64/029-book.png.h"
    };

    // File: 030-delivery-truck.png
    // Size: 1967
    static constexpr uint8_t delivery_truck[] = {
        #include "raw/icons64/030-delivery-truck.png.h"
    };

    // File: 031-garbage-car.png
    // Size: 2613
    static constexpr uint8_t garbage_car[] = {
        #include "raw/icons64/031-garbage-car.png.h"
    };

    // File: 032-hawaiian.png
    // Size: 3525
    static constexpr uint8_t hawaiian[] = {
        #include "raw/icons64/032-hawaiian.png.h"
    };

    // File: 033-rabbit.png
    // Size: 3009
    static constexpr uint8_t rabbit[] = {
        #include "raw/icons64/033-rabbit.png.h"
    };

    // File: 034-truck.png
    // Size: 1856
    static constexpr uint8_t truck[] = {
        #include "raw/icons64/034-truck.png.h"
    };

    // File: 035-crab.png
    // Size: 3412
    static constexpr uint8_t crab[] = {
        #include "raw/icons64/035-crab.png.h"
    };

    // File: 036-alpine-forget-me-not.png
    // Size: 4871
    static constexpr uint8_t alpine_forget_me_not[] = {
        #include "raw/icons64/036-alpine-forget-me-not.png.h"
    };

    // File: 037-cat.png
    // Size: 2935
    static constexpr uint8_t cat[] = {
        #include "raw/icons64/037-cat.png.h"
    };

    // File: 038-tamagochi.png
    // Size: 3159
    static constexpr uint8_t tamagochi[] = {
        #include "raw/icons64/038-tamagochi.png.h"
    };

    // File: 039-walrus.png
    // Size: 2565
    static constexpr uint8_t walrus[] = {
        #include "raw/icons64/039-walrus.png.h"
    };

    // File: 040-pea.png
    // Size: 3376
    static constexpr uint8_t pea[] = {
        #include "raw/icons64/040-pea.png.h"
    };

    // File: 041-pine-tree.png
    // Size: 2074
    static constexpr uint8_t pine_tree[] = {
        #include "raw/icons64/041-pine-tree.png.h"
    };

    // File: 042-water-gun.png
    // Size: 2201
    static constexpr uint8_t water_gun[] = {
        #include "raw/icons64/042-water-gun.png.h"
    };

    // File: 043-ladybug.png
    // Size: 3519
    static constexpr uint8_t ladybug[] = {
        #include "raw/icons64/043-ladybug.png.h"
    };

    // File: 044-mint-marigold.png
    // Size: 3626
    static constexpr uint8_t mint_marigold[] = {
        #include "raw/icons64/044-mint-marigold.png.h"
    };

    // File: 045-candy.png
    // Size: 2998
    static constexpr uint8_t candy[] = {
        #include "raw/icons64/045-candy.png.h"
    };

    // File: 046-windmill.png
    // Size: 1957
    static constexpr uint8_t windmill[] = {
        #include "raw/icons64/046-windmill.png.h"
    };

    // File: 047-hedgehog.png
    // Size: 2944
    static constexpr uint8_t hedgehog[] = {
        #include "raw/icons64/047-hedgehog.png.h"
    };

    // File: 048-freesia.png
    // Size: 4067
    static constexpr uint8_t freesia[] = {
        #include "raw/icons64/048-freesia.png.h"
    };

    // File: 049-fruits.png
    // Size: 5099
    static constexpr uint8_t fruits[] = {
        #include "raw/icons64/049-fruits.png.h"
    };

    // File: 050-rocking-horse.png
    // Size: 2441
    static constexpr uint8_t rocking_horse[] = {
        #include "raw/icons64/050-rocking-horse.png.h"
    };

    // File: 051-cat-1.png
    // Size: 4116
    static constexpr uint8_t cat_1[] = {
        #include "raw/icons64/051-cat-1.png.h"
    };

    // File: 052-geranium.png
    // Size: 4190
    static constexpr uint8_t geranium[] = {
        #include "raw/icons64/052-geranium.png.h"
    };

    // File: 053-sunlight.png
    // Size: 3940
    static constexpr uint8_t sunlight[] = {
        #include "raw/icons64/053-sunlight.png.h"
    };

    // File: 054-sword.png
    // Size: 2203
    static constexpr uint8_t sword[] = {
        #include "raw/icons64/054-sword.png.h"
    };

    // File: 055-elephant.png
    // Size: 2739
    static constexpr uint8_t elephant[] = {
        #include "raw/icons64/055-elephant.png.h"
    };

    // File: 056-lotus-flower.png
    // Size: 3862
    static constexpr uint8_t lotus_flower[] = {
        #include "raw/icons64/056-lotus-flower.png.h"
    };

    // File: 057-trees.png
    // Size: 5030
    static constexpr uint8_t trees[] = {
        #include "raw/icons64/057-trees.png.h"
    };

    // File: 058-sand-castle.png
    // Size: 1709
    static constexpr uint8_t sand_castle[] = {
        #include "raw/icons64/058-sand-castle.png.h"
    };

    // File: 059-lama.png
    // Size: 2391
    static constexpr uint8_t lama[] = {
        #include "raw/icons64/059-lama.png.h"
    };

    // File: 060-chive-blossoms.png
    // Size: 3985
    static constexpr uint8_t chive_blossoms[] = {
        #include "raw/icons64/060-chive-blossoms.png.h"
    };

    // File: 061-rain.png
    // Size: 4737
    static constexpr uint8_t rain[] = {
        #include "raw/icons64/061-rain.png.h"
    };

    // File: 062-blocks.png
    // Size: 778
    static constexpr uint8_t blocks[] = {
        #include "raw/icons64/062-blocks.png.h"
    };

    // File: 063-hippo.png
    // Size: 2896
    static constexpr uint8_t hippo[] = {
        #include "raw/icons64/063-hippo.png.h"
    };

    // File: 064-bouvardia.png
    // Size: 4734
    static constexpr uint8_t bouvardia[] = {
        #include "raw/icons64/064-bouvardia.png.h"
    };

    // File: 065-greenhouse.png
    // Size: 5884
    static constexpr uint8_t greenhouse[] = {
        #include "raw/icons64/065-greenhouse.png.h"
    };

    // File: 066-frog.png
    // Size: 2800
    static constexpr uint8_t frog[] = {
        #include "raw/icons64/066-frog.png.h"
    };

    // File: 067-pineappleweed.png
    // Size: 3543
    static constexpr uint8_t pineappleweed[] = {
        #include "raw/icons64/067-pineappleweed.png.h"
    };

    // File: 068-plant.png
    // Size: 4647
    static constexpr uint8_t plant[] = {
        #include "raw/icons64/068-plant.png.h"
    };

    // File: 069-parrot.png
    // Size: 1632
    static constexpr uint8_t parrot[] = {
        #include "raw/icons64/069-parrot.png.h"
    };

    // File: 070-bird-of-paradise.png
    // Size: 3553
    static constexpr uint8_t bird_of_paradise[] = {
        #include "raw/icons64/070-bird-of-paradise.png.h"
    };

    // File: 071-beehive.png
    // Size: 4891
    static constexpr uint8_t beehive[] = {
        #include "raw/icons64/071-beehive.png.h"
    };

    // File: 072-turtle.png
    // Size: 3263
    static constexpr uint8_t turtle[] = {
        #include "raw/icons64/072-turtle.png.h"
    };

    // File: 073-aster.png
    // Size: 4839
    static constexpr uint8_t aster[] = {
        #include "raw/icons64/073-aster.png.h"
    };

    // File: 074-watering-can.png
    // Size: 4239
    static constexpr uint8_t watering_can[] = {
        #include "raw/icons64/074-watering-can.png.h"
    };

    // File: 075-rabbit-1.png
    // Size: 2886
    static constexpr uint8_t rabbit_1[] = {
        #include "raw/icons64/075-rabbit-1.png.h"
    };

    // File: 076-snowdrop.png
    // Size: 3834
    static constexpr uint8_t snowdrop[] = {
        #include "raw/icons64/076-snowdrop.png.h"
    };

    // File: 077-carrots.png
    // Size: 4431
    static constexpr uint8_t carrots[] = {
        #include "raw/icons64/077-carrots.png.h"
    };

    // File: 078-penguin.png
    // Size: 2972
    static constexpr uint8_t penguin[] = {
        #include "raw/icons64/078-penguin.png.h"
    };

    // File: 079-borage.png
    // Size: 3991
    static constexpr uint8_t borage[] = {
        #include "raw/icons64/079-borage.png.h"
    };

    // File: 080-flower.png
    // Size: 6530
    static constexpr uint8_t flower[] = {
        #include "raw/icons64/080-flower.png.h"
    };

    // File: 081-owl.png
    // Size: 3317
    static constexpr uint8_t owl[] = {
        #include "raw/icons64/081-owl.png.h"
    };

    // File: 082-gladiolus.png
    // Size: 3448
    static constexpr uint8_t gladiolus[] = {
        #include "raw/icons64/082-gladiolus.png.h"
    };

    // File: 083-bee.png
    // Size: 2313
    static constexpr uint8_t bee[] = {
        #include "raw/icons64/083-bee.png.h"
    };

    // File: 084-tiger-lily.png
    // Size: 4221
    static constexpr uint8_t tiger_lily[] = {
        #include "raw/icons64/084-tiger-lily.png.h"
    };

    // File: 085-rhino.png
    // Size: 2888
    static constexpr uint8_t rhino[] = {
        #include "raw/icons64/085-rhino.png.h"
    };

    // File: 086-bluebell.png
    // Size: 3637
    static constexpr uint8_t bluebell[] = {
        #include "raw/icons64/086-bluebell.png.h"
    };

    // File: 087-snake.png
    // Size: 2440
    static constexpr uint8_t snake[] = {
        #include "raw/icons64/087-snake.png.h"
    };

    // File: 088-lavender.png
    // Size: 3988
    static constexpr uint8_t lavender[] = {
        #include "raw/icons64/088-lavender.png.h"
    };

    // File: 089-bullfinch.png
    // Size: 3001
    static constexpr uint8_t bullfinch[] = {
        #include "raw/icons64/089-bullfinch.png.h"
    };

    // File: 090-peony.png
    // Size: 4387
    static constexpr uint8_t peony[] = {
        #include "raw/icons64/090-peony.png.h"
    };

    // File: 091-fox.png
    // Size: 2809
    static constexpr uint8_t fox[] = {
        #include "raw/icons64/091-fox.png.h"
    };

    // File: 092-orchid.png
    // Size: 3447
    static constexpr uint8_t orchid[] = {
        #include "raw/icons64/092-orchid.png.h"
    };

    // File: 093-dog.png
    // Size: 3076
    static constexpr uint8_t dog[] = {
        #include "raw/icons64/093-dog.png.h"
    };

    // File: 094-chicken.png
    // Size: 2272
    static constexpr uint8_t chicken[] = {
        #include "raw/icons64/094-chicken.png.h"
    };

    // File: 095-panda.png
    // Size: 3385
    static constexpr uint8_t panda[] = {
        #include "raw/icons64/095-panda.png.h"
    };

    // File: 096-gorilla.png
    // Size: 3443
    static constexpr uint8_t gorilla[] = {
        #include "raw/icons64/096-gorilla.png.h"
    };

    // File: 097-squid.png
    // Size: 2910
    static constexpr uint8_t squid[] = {
        #include "raw/icons64/097-squid.png.h"
    };

    // File: 098-chameleon.png
    // Size: 3142
    static constexpr uint8_t chameleon[] = {
        #include "raw/icons64/098-chameleon.png.h"
    };

    // File: 099-cow.png
    // Size: 3161
    static constexpr uint8_t cow[] = {
        #include "raw/icons64/099-cow.png.h"
    };

    // File: 100-buffalo.png
    // Size: 2898
    static constexpr uint8_t buffalo[] = {
        #include "raw/icons64/100-buffalo.png.h"
    };

    // File: 101-horse.png
    // Size: 3046
    static constexpr uint8_t horse[] = {
        #include "raw/icons64/101-horse.png.h"
    };

    // File: 102-platypus.png
    // Size: 2457
    static constexpr uint8_t platypus[] = {
        #include "raw/icons64/102-platypus.png.h"
    };

    // File: 103-sloth.png
    // Size: 3379
    static constexpr uint8_t sloth[] = {
        #include "raw/icons64/103-sloth.png.h"
    };

    // File: 104-stingray.png
    // Size: 2356
    static constexpr uint8_t stingray[] = {
        #include "raw/icons64/104-stingray.png.h"
    };

    // File: 105-zebra.png
    // Size: 4152
    static constexpr uint8_t zebra[] = {
        #include "raw/icons64/105-zebra.png.h"
    };

    // File: 106-crocodile.png
    // Size: 3171
    static constexpr uint8_t crocodile[] = {
        #include "raw/icons64/106-crocodile.png.h"
    };

    // File: 107-shark.png
    // Size: 2511
    static constexpr uint8_t shark[] = {
        #include "raw/icons64/107-shark.png.h"
    };

    // File: 108-camel.png
    // Size: 2907
    static constexpr uint8_t camel[] = {
        #include "raw/icons64/108-camel.png.h"
    };

    // File: 109-butterfly.png
    // Size: 2372
    static constexpr uint8_t butterfly[] = {
        #include "raw/icons64/109-butterfly.png.h"
    };

    // File: 110-boar.png
    // Size: 3021
    static constexpr uint8_t boar[] = {
        #include "raw/icons64/110-boar.png.h"
    };

    // File: 111-deer.png
    // Size: 2919
    static constexpr uint8_t deer[] = {
        #include "raw/icons64/111-deer.png.h"
    };

    // File: 112-whale.png
    // Size: 2423
    static constexpr uint8_t whale[] = {
        #include "raw/icons64/112-whale.png.h"
    };

    // File: 113-spider.png
    // Size: 3832
    static constexpr uint8_t spider[] = {
        #include "raw/icons64/113-spider.png.h"
    };

    // File: 114-bat.png
    // Size: 3133
    static constexpr uint8_t bat[] = {
        #include "raw/icons64/114-bat.png.h"
    };

    // File: 115-beaver.png
    // Size: 3128
    static constexpr uint8_t beaver[] = {
        #include "raw/icons64/115-beaver.png.h"
    };

    // File: 116-giraffe.png
    // Size: 2752
    static constexpr uint8_t giraffe[] = {
        #include "raw/icons64/116-giraffe.png.h"
    };

    // File: 117-microphone.png
    // Size: 3240
    static constexpr uint8_t microphone[] = {
        #include "raw/icons64/117-microphone.png.h"
    };

    // File: 118-applications.png
    // Size: 2046
    static constexpr uint8_t applications[] = {
        #include "raw/icons64/118-applications.png.h"
    };

    // File: 119-gameboy.png
    // Size: 1560
    static constexpr uint8_t gameboy[] = {
        #include "raw/icons64/119-gameboy.png.h"
    };

    // File: 120-sand-clock.png
    // Size: 1853
    static constexpr uint8_t sand_clock[] = {
        #include "raw/icons64/120-sand-clock.png.h"
    };

    // File: 121-chase.png
    // Size: 4002
    static constexpr uint8_t chase[] = {
        #include "raw/icons64/121-chase.png.h"
    };

    // File: 122-ambulance.png
    // Size: 2049
    static constexpr uint8_t ambulance[] = {
        #include "raw/icons64/122-ambulance.png.h"
    };

    // File: 123-fairy-tale.png
    // Size: 3654
    static constexpr uint8_t fairy_tale[] = {
        #include "raw/icons64/123-fairy-tale.png.h"
    };

    // File: 124-fairy-1.png
    // Size: 2906
    static constexpr uint8_t fairy_1[] = {
        #include "raw/icons64/124-fairy-1.png.h"
    };

    // File: 125-fairy-tale-1.png
    // Size: 3865
    static constexpr uint8_t fairy_tale_1[] = {
        #include "raw/icons64/125-fairy-tale-1.png.h"
    };

    // File: 126-cinderella-carriage.png
    // Size: 4254
    static constexpr uint8_t cinderella_carriage[] = {
        #include "raw/icons64/126-cinderella-carriage.png.h"
    };

    // File: 127-cinderella-shoe.png
    // Size: 2824
    static constexpr uint8_t cinderella_shoe[] = {
        #include "raw/icons64/127-cinderella-shoe.png.h"
    };

    // File: 128-forklift.png
    // Size: 2932
    static constexpr uint8_t forklift[] = {
        #include "raw/icons64/128-forklift.png.h"
    };

    // File: 129-lynx.png
    // Size: 5020
    static constexpr uint8_t lynx[] = {
        #include "raw/icons64/129-lynx.png.h"
    };

    // File: 130-steering-wheel.png
    // Size: 3948
    static constexpr uint8_t steering_wheel[] = {
        #include "raw/icons64/130-steering-wheel.png.h"
    };

    // File: 131-paint-palette.png
    // Size: 3267
    static constexpr uint8_t paint_palette[] = {
        #include "raw/icons64/131-paint-palette.png.h"
    };

    // File: 132-horn.png
    // Size: 1428
    static constexpr uint8_t horn[] = {
        #include "raw/icons64/132-horn.png.h"
    };

    // File: 133-frog-1.png
    // Size: 2973
    static constexpr uint8_t frog_1[] = {
        #include "raw/icons64/133-frog-1.png.h"
    };

    // File: 134-digger.png
    // Size: 2327
    static constexpr uint8_t digger[] = {
        #include "raw/icons64/134-digger.png.h"
    };

    // File: 135-toy-train.png
    // Size: 3087
    static constexpr uint8_t toy_train[] = {
        #include "raw/icons64/135-toy-train.png.h"
    };

    // File: 136-sailing-boat.png
    // Size: 2196
    static constexpr uint8_t sailing_boat[] = {
        #include "raw/icons64/136-sailing-boat.png.h"
    };

    // File: 137-fire-truck.png
    // Size: 2859
    static constexpr uint8_t fire_truck[] = {
        #include "raw/icons64/137-fire-truck.png.h"
    };

    // File: 138-bulldozer.png
    // Size: 2545
    static constexpr uint8_t bulldozer[] = {
        #include "raw/icons64/138-bulldozer.png.h"
    };

    // File: 139-orca.png
    // Size: 3183
    static constexpr uint8_t orca[] = {
        #include "raw/icons64/139-orca.png.h"
    };

    // File: 140-pet.png
    // Size: 3075
    static constexpr uint8_t pet[] = {
        #include "raw/icons64/140-pet.png.h"
    };

    // File: 141-pen-drive.png
    // Size: 1184
    static constexpr uint8_t pen_drive[] = {
        #include "raw/icons64/141-pen-drive.png.h"
    };

    // File: 142-ping-pong.png
    // Size: 2979
    static constexpr uint8_t ping_pong[] = {
        #include "raw/icons64/142-ping-pong.png.h"
    };

    // File: 143-snake-1.png
    // Size: 2574
    static constexpr uint8_t snake_1[] = {
        #include "raw/icons64/143-snake-1.png.h"
    };

    // File: 144-board-game.png
    // Size: 1949
    static constexpr uint8_t board_game[] = {
        #include "raw/icons64/144-board-game.png.h"
    };

    // File: 145-dices.png
    // Size: 2881
    static constexpr uint8_t dices[] = {
        #include "raw/icons64/145-dices.png.h"
    };

    // File: 146-swords.png
    // Size: 3690
    static constexpr uint8_t swords[] = {
        #include "raw/icons64/146-swords.png.h"
    };

    // File: 147-mosaic.png
    // Size: 1343
    static constexpr uint8_t mosaic[] = {
        #include "raw/icons64/147-mosaic.png.h"
    };

    // File: 148-clock.png
    // Size: 4080
    static constexpr uint8_t clock[] = {
        #include "raw/icons64/148-clock.png.h"
    };

    // File: 149-alien.png
    // Size: 2125
    static constexpr uint8_t alien[] = {
        #include "raw/icons64/149-alien.png.h"
    };

    // File: 150-alien-1.png
    // Size: 3045
    static constexpr uint8_t alien_1[] = {
        #include "raw/icons64/150-alien-1.png.h"
    };

    // File: 151-alien-2.png
    // Size: 3371
    static constexpr uint8_t alien_2[] = {
        #include "raw/icons64/151-alien-2.png.h"
    };

    // File: 152-space.png
    // Size: 2552
    static constexpr uint8_t space[] = {
        #include "raw/icons64/152-space.png.h"
    };

    // File: 153-tetris.png
    // Size: 667
    static constexpr uint8_t tetris[] = {
        #include "raw/icons64/153-tetris.png.h"
    };

    // File: 154-car-light.png
    // Size: 1794
    static constexpr uint8_t car_light[] = {
        #include "raw/icons64/154-car-light.png.h"
    };

    // File: 155-arcade.png
    // Size: 1967
    static constexpr uint8_t arcade[] = {
        #include "raw/icons64/155-arcade.png.h"
    };

    // File: 156-like.png
    // Size: 1576
    static constexpr uint8_t like[] = {
        #include "raw/icons64/156-like.png.h"
    };

    // File: 157-ghost.png
    // Size: 1057
    static constexpr uint8_t ghost[] = {
        #include "raw/icons64/157-ghost.png.h"
    };

    // File: 158-multimedia.png
    // Size: 3526
    static constexpr uint8_t multimedia[] = {
        #include "raw/icons64/158-multimedia.png.h"
    };

    // File: 159-mouse.png
    // Size: 2245
    static constexpr uint8_t mouse[] = {
        #include "raw/icons64/159-mouse.png.h"
    };

    // File: 160-pig.png
    // Size: 2371
    static constexpr uint8_t pig[] = {
        #include "raw/icons64/160-pig.png.h"
    };

    // File: 161-mushroom.png
    // Size: 3058
    static constexpr uint8_t mushroom[] = {
        #include "raw/icons64/161-mushroom.png.h"
    };

    // File: 162-duck.png
    // Size: 2803
    static constexpr uint8_t duck[] = {
        #include "raw/icons64/162-duck.png.h"
    };

    // File: 163-fairy-2.png
    // Size: 3362
    static constexpr uint8_t fairy_2[] = {
        #include "raw/icons64/163-fairy-2.png.h"
    };

    // File: 164-fairy-3.png
    // Size: 3594
    static constexpr uint8_t fairy_3[] = {
        #include "raw/icons64/164-fairy-3.png.h"
    };

    // File: 165-detective.png
    // Size: 3577
    static constexpr uint8_t detective[] = {
        #include "raw/icons64/165-detective.png.h"
    };

    // File: 166-dragon-boat.png
    // Size: 3238
    static constexpr uint8_t dragon_boat[] = {
        #include "raw/icons64/166-dragon-boat.png.h"
    };

    // File: 167-witch.png
    // Size: 3566
    static constexpr uint8_t witch[] = {
        #include "raw/icons64/167-witch.png.h"
    };

    // File: 168-wardrobe.png
    // Size: 1608
    static constexpr uint8_t wardrobe[] = {
        #include "raw/icons64/168-wardrobe.png.h"
    };

    // File: 169-siren.png
    // Size: 1063
    static constexpr uint8_t siren[] = {
        #include "raw/icons64/169-siren.png.h"
    };

    // File: 170-car-engine.png
    // Size: 4694
    static constexpr uint8_t car_engine[] = {
        #include "raw/icons64/170-car-engine.png.h"
    };

    // File: 171-screenshot.png
    // Size: 2072
    static constexpr uint8_t screenshot[] = {
        #include "raw/icons64/171-screenshot.png.h"
    };

    // File: 172-squirrel.png
    // Size: 3031
    static constexpr uint8_t squirrel[] = {
        #include "raw/icons64/172-squirrel.png.h"
    };

    // File: 173-owl-1.png
    // Size: 3823
    static constexpr uint8_t owl_1[] = {
        #include "raw/icons64/173-owl-1.png.h"
    };

    // File: 174-fish.png
    // Size: 2783
    static constexpr uint8_t fish[] = {
        #include "raw/icons64/174-fish.png.h"
    };

    // File: 175-bird.png
    // Size: 2477
    static constexpr uint8_t bird[] = {
        #include "raw/icons64/175-bird.png.h"
    };

    // File: 176-shiba.png
    // Size: 3530
    static constexpr uint8_t shiba[] = {
        #include "raw/icons64/176-shiba.png.h"
    };

    // File: 177-bike.png
    // Size: 4640
    static constexpr uint8_t bike[] = {
        #include "raw/icons64/177-bike.png.h"
    };

    // File: 178-buggy.png
    // Size: 3641
    static constexpr uint8_t buggy[] = {
        #include "raw/icons64/178-buggy.png.h"
    };

    // File: 179-bicycle.png
    // Size: 3369
    static constexpr uint8_t bicycle[] = {
        #include "raw/icons64/179-bicycle.png.h"
    };
} // namespace rckid::assets::icons64
