#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  assets/icons/default/64 rckid/assets/icons_default_64.h --raw-path raw/icons --namespace rckid::assets::icons_default_64
 */

namespace rckid::assets::icons_default_64 {

    // File: assets/icons/default/64/001-game-controller.png
    // Size: 3058
    static constexpr uint8_t game_controller[] = {
        #include "raw/icons/game_controller.inc.h"
    };

    // File: assets/icons/default/64/002-rc-car.png
    // Size: 2955
    static constexpr uint8_t rc_car[] = {
        #include "raw/icons/rc_car.inc.h"
    };

    // File: assets/icons/default/64/003-music.png
    // Size: 2532
    static constexpr uint8_t music[] = {
        #include "raw/icons/music.inc.h"
    };

    // File: assets/icons/default/64/004-flashlight.png
    // Size: 2323
    static constexpr uint8_t flashlight[] = {
        #include "raw/icons/flashlight.inc.h"
    };

    // File: assets/icons/default/64/005-film-slate.png
    // Size: 2563
    static constexpr uint8_t film_slate[] = {
        #include "raw/icons/film_slate.inc.h"
    };

    // File: assets/icons/default/64/006-baby-crib.png
    // Size: 3068
    static constexpr uint8_t baby_crib[] = {
        #include "raw/icons/baby_crib.inc.h"
    };

    // File: assets/icons/default/64/007-baby-monitor.png
    // Size: 2168
    static constexpr uint8_t baby_monitor[] = {
        #include "raw/icons/baby_monitor.inc.h"
    };

    // File: assets/icons/default/64/008-unicorn.png
    // Size: 5834
    static constexpr uint8_t unicorn[] = {
        #include "raw/icons/unicorn.inc.h"
    };

    // File: assets/icons/default/64/009-brightness.png
    // Size: 1908
    static constexpr uint8_t brightness[] = {
        #include "raw/icons/brightness.inc.h"
    };

    // File: assets/icons/default/64/010-high-volume.png
    // Size: 2396
    static constexpr uint8_t high_volume[] = {
        #include "raw/icons/high_volume.inc.h"
    };

    // File: assets/icons/default/64/011-power-off.png
    // Size: 3139
    static constexpr uint8_t power_off[] = {
        #include "raw/icons/power_off.inc.h"
    };

    // File: assets/icons/default/64/012-airplane-mode.png
    // Size: 1592
    static constexpr uint8_t airplane_mode[] = {
        #include "raw/icons/airplane_mode.inc.h"
    };

    // File: assets/icons/default/64/013-settings.png
    // Size: 2825
    static constexpr uint8_t settings[] = {
        #include "raw/icons/settings.inc.h"
    };

    // File: assets/icons/default/64/014-info.png
    // Size: 1707
    static constexpr uint8_t info[] = {
        #include "raw/icons/info.inc.h"
    };

    // File: assets/icons/default/64/015-alarm-clock.png
    // Size: 4855
    static constexpr uint8_t alarm_clock[] = {
        #include "raw/icons/alarm_clock.inc.h"
    };

    // File: assets/icons/default/64/016-wifi.png
    // Size: 2244
    static constexpr uint8_t wifi[] = {
        #include "raw/icons/wifi.inc.h"
    };

    // File: assets/icons/default/64/017-signal.png
    // Size: 3456
    static constexpr uint8_t signal[] = {
        #include "raw/icons/signal.inc.h"
    };

    // File: assets/icons/default/64/018-cancel.png
    // Size: 2359
    static constexpr uint8_t cancel[] = {
        #include "raw/icons/cancel.inc.h"
    };

    // File: assets/icons/default/64/019-sad.png
    // Size: 1699
    static constexpr uint8_t sad[] = {
        #include "raw/icons/sad.inc.h"
    };

    // File: assets/icons/default/64/020-poo.png
    // Size: 2396
    static constexpr uint8_t poo[] = {
        #include "raw/icons/poo.inc.h"
    };

    // File: assets/icons/default/64/021-birthday-cake.png
    // Size: 1876
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons/birthday_cake.inc.h"
    };

    // File: assets/icons/default/64/022-presents.png
    // Size: 3299
    static constexpr uint8_t presents[] = {
        #include "raw/icons/presents.inc.h"
    };

    // File: assets/icons/default/64/023-easter.png
    // Size: 3725
    static constexpr uint8_t easter[] = {
        #include "raw/icons/easter.inc.h"
    };

    // File: assets/icons/default/64/024-santa-hat.png
    // Size: 2516
    static constexpr uint8_t santa_hat[] = {
        #include "raw/icons/santa_hat.inc.h"
    };

    // File: assets/icons/default/64/025-heart.png
    // Size: 1981
    static constexpr uint8_t heart[] = {
        #include "raw/icons/heart.inc.h"
    };

    // File: assets/icons/default/64/026-magic-wand.png
    // Size: 2836
    static constexpr uint8_t magic_wand[] = {
        #include "raw/icons/magic_wand.inc.h"
    };

    // File: assets/icons/default/64/027-fairy.png
    // Size: 3027
    static constexpr uint8_t fairy[] = {
        #include "raw/icons/fairy.inc.h"
    };

    // File: assets/icons/default/64/028-unicorn-1.png
    // Size: 3341
    static constexpr uint8_t unicorn_1[] = {
        #include "raw/icons/unicorn_1.inc.h"
    };

    // File: assets/icons/default/64/029-book.png
    // Size: 3735
    static constexpr uint8_t book[] = {
        #include "raw/icons/book.inc.h"
    };

    // File: assets/icons/default/64/030-delivery-truck.png
    // Size: 1967
    static constexpr uint8_t delivery_truck[] = {
        #include "raw/icons/delivery_truck.inc.h"
    };

    // File: assets/icons/default/64/031-garbage-car.png
    // Size: 2613
    static constexpr uint8_t garbage_car[] = {
        #include "raw/icons/garbage_car.inc.h"
    };

    // File: assets/icons/default/64/032-hawaiian.png
    // Size: 3525
    static constexpr uint8_t hawaiian[] = {
        #include "raw/icons/hawaiian.inc.h"
    };

    // File: assets/icons/default/64/033-rabbit.png
    // Size: 3009
    static constexpr uint8_t rabbit[] = {
        #include "raw/icons/rabbit.inc.h"
    };

    // File: assets/icons/default/64/034-truck.png
    // Size: 1856
    static constexpr uint8_t truck[] = {
        #include "raw/icons/truck.inc.h"
    };

    // File: assets/icons/default/64/035-crab.png
    // Size: 3412
    static constexpr uint8_t crab[] = {
        #include "raw/icons/crab.inc.h"
    };

    // File: assets/icons/default/64/036-alpine-forget-me-not.png
    // Size: 4871
    static constexpr uint8_t alpine_forget_me_not[] = {
        #include "raw/icons/alpine_forget_me_not.inc.h"
    };

    // File: assets/icons/default/64/037-cat.png
    // Size: 2935
    static constexpr uint8_t cat[] = {
        #include "raw/icons/cat.inc.h"
    };

    // File: assets/icons/default/64/038-tamagochi.png
    // Size: 3159
    static constexpr uint8_t tamagochi[] = {
        #include "raw/icons/tamagochi.inc.h"
    };

    // File: assets/icons/default/64/039-walrus.png
    // Size: 2565
    static constexpr uint8_t walrus[] = {
        #include "raw/icons/walrus.inc.h"
    };

    // File: assets/icons/default/64/040-pea.png
    // Size: 3376
    static constexpr uint8_t pea[] = {
        #include "raw/icons/pea.inc.h"
    };

    // File: assets/icons/default/64/041-pine-tree.png
    // Size: 2074
    static constexpr uint8_t pine_tree[] = {
        #include "raw/icons/pine_tree.inc.h"
    };

    // File: assets/icons/default/64/042-water-gun.png
    // Size: 2201
    static constexpr uint8_t water_gun[] = {
        #include "raw/icons/water_gun.inc.h"
    };

    // File: assets/icons/default/64/043-ladybug.png
    // Size: 3519
    static constexpr uint8_t ladybug[] = {
        #include "raw/icons/ladybug.inc.h"
    };

    // File: assets/icons/default/64/044-mint-marigold.png
    // Size: 3626
    static constexpr uint8_t mint_marigold[] = {
        #include "raw/icons/mint_marigold.inc.h"
    };

    // File: assets/icons/default/64/045-candy.png
    // Size: 2998
    static constexpr uint8_t candy[] = {
        #include "raw/icons/candy.inc.h"
    };

    // File: assets/icons/default/64/046-windmill.png
    // Size: 1957
    static constexpr uint8_t windmill[] = {
        #include "raw/icons/windmill.inc.h"
    };

    // File: assets/icons/default/64/047-hedgehog.png
    // Size: 2944
    static constexpr uint8_t hedgehog[] = {
        #include "raw/icons/hedgehog.inc.h"
    };

    // File: assets/icons/default/64/048-freesia.png
    // Size: 4067
    static constexpr uint8_t freesia[] = {
        #include "raw/icons/freesia.inc.h"
    };

    // File: assets/icons/default/64/049-fruits.png
    // Size: 5099
    static constexpr uint8_t fruits[] = {
        #include "raw/icons/fruits.inc.h"
    };

    // File: assets/icons/default/64/050-rocking-horse.png
    // Size: 2441
    static constexpr uint8_t rocking_horse[] = {
        #include "raw/icons/rocking_horse.inc.h"
    };

    // File: assets/icons/default/64/051-cat-1.png
    // Size: 4116
    static constexpr uint8_t cat_1[] = {
        #include "raw/icons/cat_1.inc.h"
    };

    // File: assets/icons/default/64/052-geranium.png
    // Size: 4190
    static constexpr uint8_t geranium[] = {
        #include "raw/icons/geranium.inc.h"
    };

    // File: assets/icons/default/64/053-sunlight.png
    // Size: 3940
    static constexpr uint8_t sunlight[] = {
        #include "raw/icons/sunlight.inc.h"
    };

    // File: assets/icons/default/64/054-sword.png
    // Size: 2203
    static constexpr uint8_t sword[] = {
        #include "raw/icons/sword.inc.h"
    };

    // File: assets/icons/default/64/055-elephant.png
    // Size: 2739
    static constexpr uint8_t elephant[] = {
        #include "raw/icons/elephant.inc.h"
    };

    // File: assets/icons/default/64/056-lotus-flower.png
    // Size: 3862
    static constexpr uint8_t lotus_flower[] = {
        #include "raw/icons/lotus_flower.inc.h"
    };

    // File: assets/icons/default/64/057-trees.png
    // Size: 5030
    static constexpr uint8_t trees[] = {
        #include "raw/icons/trees.inc.h"
    };

    // File: assets/icons/default/64/058-sand-castle.png
    // Size: 1709
    static constexpr uint8_t sand_castle[] = {
        #include "raw/icons/sand_castle.inc.h"
    };

    // File: assets/icons/default/64/059-lama.png
    // Size: 2391
    static constexpr uint8_t lama[] = {
        #include "raw/icons/lama.inc.h"
    };

    // File: assets/icons/default/64/060-chive-blossoms.png
    // Size: 3985
    static constexpr uint8_t chive_blossoms[] = {
        #include "raw/icons/chive_blossoms.inc.h"
    };

    // File: assets/icons/default/64/061-rain.png
    // Size: 4737
    static constexpr uint8_t rain[] = {
        #include "raw/icons/rain.inc.h"
    };

    // File: assets/icons/default/64/062-blocks.png
    // Size: 778
    static constexpr uint8_t blocks[] = {
        #include "raw/icons/blocks.inc.h"
    };

    // File: assets/icons/default/64/063-hippo.png
    // Size: 2896
    static constexpr uint8_t hippo[] = {
        #include "raw/icons/hippo.inc.h"
    };

    // File: assets/icons/default/64/064-bouvardia.png
    // Size: 4734
    static constexpr uint8_t bouvardia[] = {
        #include "raw/icons/bouvardia.inc.h"
    };

    // File: assets/icons/default/64/065-greenhouse.png
    // Size: 5884
    static constexpr uint8_t greenhouse[] = {
        #include "raw/icons/greenhouse.inc.h"
    };

    // File: assets/icons/default/64/066-frog.png
    // Size: 2800
    static constexpr uint8_t frog[] = {
        #include "raw/icons/frog.inc.h"
    };

    // File: assets/icons/default/64/067-pineappleweed.png
    // Size: 3543
    static constexpr uint8_t pineappleweed[] = {
        #include "raw/icons/pineappleweed.inc.h"
    };

    // File: assets/icons/default/64/068-plant.png
    // Size: 4647
    static constexpr uint8_t plant[] = {
        #include "raw/icons/plant.inc.h"
    };

    // File: assets/icons/default/64/069-parrot.png
    // Size: 1632
    static constexpr uint8_t parrot[] = {
        #include "raw/icons/parrot.inc.h"
    };

    // File: assets/icons/default/64/070-bird-of-paradise.png
    // Size: 3553
    static constexpr uint8_t bird_of_paradise[] = {
        #include "raw/icons/bird_of_paradise.inc.h"
    };

    // File: assets/icons/default/64/071-beehive.png
    // Size: 4891
    static constexpr uint8_t beehive[] = {
        #include "raw/icons/beehive.inc.h"
    };

    // File: assets/icons/default/64/072-turtle.png
    // Size: 3263
    static constexpr uint8_t turtle[] = {
        #include "raw/icons/turtle.inc.h"
    };

    // File: assets/icons/default/64/073-aster.png
    // Size: 4839
    static constexpr uint8_t aster[] = {
        #include "raw/icons/aster.inc.h"
    };

    // File: assets/icons/default/64/074-watering-can.png
    // Size: 4239
    static constexpr uint8_t watering_can[] = {
        #include "raw/icons/watering_can.inc.h"
    };

    // File: assets/icons/default/64/075-rabbit-1.png
    // Size: 2886
    static constexpr uint8_t rabbit_1[] = {
        #include "raw/icons/rabbit_1.inc.h"
    };

    // File: assets/icons/default/64/076-snowdrop.png
    // Size: 3834
    static constexpr uint8_t snowdrop[] = {
        #include "raw/icons/snowdrop.inc.h"
    };

    // File: assets/icons/default/64/077-carrots.png
    // Size: 4431
    static constexpr uint8_t carrots[] = {
        #include "raw/icons/carrots.inc.h"
    };

    // File: assets/icons/default/64/078-penguin.png
    // Size: 2972
    static constexpr uint8_t penguin[] = {
        #include "raw/icons/penguin.inc.h"
    };

    // File: assets/icons/default/64/079-borage.png
    // Size: 3991
    static constexpr uint8_t borage[] = {
        #include "raw/icons/borage.inc.h"
    };

    // File: assets/icons/default/64/080-flower.png
    // Size: 6530
    static constexpr uint8_t flower[] = {
        #include "raw/icons/flower.inc.h"
    };

    // File: assets/icons/default/64/081-owl.png
    // Size: 3317
    static constexpr uint8_t owl[] = {
        #include "raw/icons/owl.inc.h"
    };

    // File: assets/icons/default/64/082-gladiolus.png
    // Size: 3448
    static constexpr uint8_t gladiolus[] = {
        #include "raw/icons/gladiolus.inc.h"
    };

    // File: assets/icons/default/64/083-bee.png
    // Size: 2313
    static constexpr uint8_t bee[] = {
        #include "raw/icons/bee.inc.h"
    };

    // File: assets/icons/default/64/084-tiger-lily.png
    // Size: 4221
    static constexpr uint8_t tiger_lily[] = {
        #include "raw/icons/tiger_lily.inc.h"
    };

    // File: assets/icons/default/64/085-rhino.png
    // Size: 2888
    static constexpr uint8_t rhino[] = {
        #include "raw/icons/rhino.inc.h"
    };

    // File: assets/icons/default/64/086-bluebell.png
    // Size: 3637
    static constexpr uint8_t bluebell[] = {
        #include "raw/icons/bluebell.inc.h"
    };

    // File: assets/icons/default/64/087-snake.png
    // Size: 2440
    static constexpr uint8_t snake[] = {
        #include "raw/icons/snake.inc.h"
    };

    // File: assets/icons/default/64/088-lavender.png
    // Size: 3988
    static constexpr uint8_t lavender[] = {
        #include "raw/icons/lavender.inc.h"
    };

    // File: assets/icons/default/64/089-bullfinch.png
    // Size: 3001
    static constexpr uint8_t bullfinch[] = {
        #include "raw/icons/bullfinch.inc.h"
    };

    // File: assets/icons/default/64/090-peony.png
    // Size: 4387
    static constexpr uint8_t peony[] = {
        #include "raw/icons/peony.inc.h"
    };

    // File: assets/icons/default/64/091-fox.png
    // Size: 2809
    static constexpr uint8_t fox[] = {
        #include "raw/icons/fox.inc.h"
    };

    // File: assets/icons/default/64/092-orchid.png
    // Size: 3447
    static constexpr uint8_t orchid[] = {
        #include "raw/icons/orchid.inc.h"
    };

    // File: assets/icons/default/64/093-dog.png
    // Size: 3076
    static constexpr uint8_t dog[] = {
        #include "raw/icons/dog.inc.h"
    };

    // File: assets/icons/default/64/094-chicken.png
    // Size: 2272
    static constexpr uint8_t chicken[] = {
        #include "raw/icons/chicken.inc.h"
    };

    // File: assets/icons/default/64/095-panda.png
    // Size: 3385
    static constexpr uint8_t panda[] = {
        #include "raw/icons/panda.inc.h"
    };

    // File: assets/icons/default/64/096-gorilla.png
    // Size: 3443
    static constexpr uint8_t gorilla[] = {
        #include "raw/icons/gorilla.inc.h"
    };

    // File: assets/icons/default/64/097-squid.png
    // Size: 2910
    static constexpr uint8_t squid[] = {
        #include "raw/icons/squid.inc.h"
    };

    // File: assets/icons/default/64/098-chameleon.png
    // Size: 3142
    static constexpr uint8_t chameleon[] = {
        #include "raw/icons/chameleon.inc.h"
    };

    // File: assets/icons/default/64/099-cow.png
    // Size: 3161
    static constexpr uint8_t cow[] = {
        #include "raw/icons/cow.inc.h"
    };

    // File: assets/icons/default/64/100-buffalo.png
    // Size: 2898
    static constexpr uint8_t buffalo[] = {
        #include "raw/icons/buffalo.inc.h"
    };

    // File: assets/icons/default/64/101-horse.png
    // Size: 3046
    static constexpr uint8_t horse[] = {
        #include "raw/icons/horse.inc.h"
    };

    // File: assets/icons/default/64/102-platypus.png
    // Size: 2457
    static constexpr uint8_t platypus[] = {
        #include "raw/icons/platypus.inc.h"
    };

    // File: assets/icons/default/64/103-sloth.png
    // Size: 3379
    static constexpr uint8_t sloth[] = {
        #include "raw/icons/sloth.inc.h"
    };

    // File: assets/icons/default/64/104-stingray.png
    // Size: 2356
    static constexpr uint8_t stingray[] = {
        #include "raw/icons/stingray.inc.h"
    };

    // File: assets/icons/default/64/105-zebra.png
    // Size: 4152
    static constexpr uint8_t zebra[] = {
        #include "raw/icons/zebra.inc.h"
    };

    // File: assets/icons/default/64/106-crocodile.png
    // Size: 3171
    static constexpr uint8_t crocodile[] = {
        #include "raw/icons/crocodile.inc.h"
    };

    // File: assets/icons/default/64/107-shark.png
    // Size: 2511
    static constexpr uint8_t shark[] = {
        #include "raw/icons/shark.inc.h"
    };

    // File: assets/icons/default/64/108-camel.png
    // Size: 2907
    static constexpr uint8_t camel[] = {
        #include "raw/icons/camel.inc.h"
    };

    // File: assets/icons/default/64/109-butterfly.png
    // Size: 2372
    static constexpr uint8_t butterfly[] = {
        #include "raw/icons/butterfly.inc.h"
    };

    // File: assets/icons/default/64/110-boar.png
    // Size: 3021
    static constexpr uint8_t boar[] = {
        #include "raw/icons/boar.inc.h"
    };

    // File: assets/icons/default/64/111-deer.png
    // Size: 2919
    static constexpr uint8_t deer[] = {
        #include "raw/icons/deer.inc.h"
    };

    // File: assets/icons/default/64/112-whale.png
    // Size: 2423
    static constexpr uint8_t whale[] = {
        #include "raw/icons/whale.inc.h"
    };

    // File: assets/icons/default/64/113-spider.png
    // Size: 3832
    static constexpr uint8_t spider[] = {
        #include "raw/icons/spider.inc.h"
    };

    // File: assets/icons/default/64/114-bat.png
    // Size: 3133
    static constexpr uint8_t bat[] = {
        #include "raw/icons/bat.inc.h"
    };

    // File: assets/icons/default/64/115-beaver.png
    // Size: 3128
    static constexpr uint8_t beaver[] = {
        #include "raw/icons/beaver.inc.h"
    };

    // File: assets/icons/default/64/116-giraffe.png
    // Size: 2752
    static constexpr uint8_t giraffe[] = {
        #include "raw/icons/giraffe.inc.h"
    };

    // File: assets/icons/default/64/117-microphone.png
    // Size: 3240
    static constexpr uint8_t microphone[] = {
        #include "raw/icons/microphone.inc.h"
    };

    // File: assets/icons/default/64/118-applications.png
    // Size: 2046
    static constexpr uint8_t applications[] = {
        #include "raw/icons/applications.inc.h"
    };

    // File: assets/icons/default/64/119-gameboy.png
    // Size: 1560
    static constexpr uint8_t gameboy[] = {
        #include "raw/icons/gameboy.inc.h"
    };

    // File: assets/icons/default/64/120-sand-clock.png
    // Size: 1853
    static constexpr uint8_t sand_clock[] = {
        #include "raw/icons/sand_clock.inc.h"
    };

    // File: assets/icons/default/64/121-chase.png
    // Size: 4002
    static constexpr uint8_t chase[] = {
        #include "raw/icons/chase.inc.h"
    };

    // File: assets/icons/default/64/122-ambulance.png
    // Size: 2049
    static constexpr uint8_t ambulance[] = {
        #include "raw/icons/ambulance.inc.h"
    };

    // File: assets/icons/default/64/123-fairy-tale.png
    // Size: 3654
    static constexpr uint8_t fairy_tale[] = {
        #include "raw/icons/fairy_tale.inc.h"
    };

    // File: assets/icons/default/64/124-fairy-1.png
    // Size: 2906
    static constexpr uint8_t fairy_1[] = {
        #include "raw/icons/fairy_1.inc.h"
    };

    // File: assets/icons/default/64/125-fairy-tale-1.png
    // Size: 3865
    static constexpr uint8_t fairy_tale_1[] = {
        #include "raw/icons/fairy_tale_1.inc.h"
    };

    // File: assets/icons/default/64/126-cinderella-carriage.png
    // Size: 4254
    static constexpr uint8_t cinderella_carriage[] = {
        #include "raw/icons/cinderella_carriage.inc.h"
    };

    // File: assets/icons/default/64/127-cinderella-shoe.png
    // Size: 2824
    static constexpr uint8_t cinderella_shoe[] = {
        #include "raw/icons/cinderella_shoe.inc.h"
    };

    // File: assets/icons/default/64/128-forklift.png
    // Size: 2932
    static constexpr uint8_t forklift[] = {
        #include "raw/icons/forklift.inc.h"
    };

    // File: assets/icons/default/64/129-lynx.png
    // Size: 5020
    static constexpr uint8_t lynx[] = {
        #include "raw/icons/lynx.inc.h"
    };

    // File: assets/icons/default/64/130-steering-wheel.png
    // Size: 3948
    static constexpr uint8_t steering_wheel[] = {
        #include "raw/icons/steering_wheel.inc.h"
    };

    // File: assets/icons/default/64/131-paint-palette.png
    // Size: 3267
    static constexpr uint8_t paint_palette[] = {
        #include "raw/icons/paint_palette.inc.h"
    };

    // File: assets/icons/default/64/132-horn.png
    // Size: 1428
    static constexpr uint8_t horn[] = {
        #include "raw/icons/horn.inc.h"
    };

    // File: assets/icons/default/64/133-frog-1.png
    // Size: 2973
    static constexpr uint8_t frog_1[] = {
        #include "raw/icons/frog_1.inc.h"
    };

    // File: assets/icons/default/64/134-digger.png
    // Size: 2327
    static constexpr uint8_t digger[] = {
        #include "raw/icons/digger.inc.h"
    };

    // File: assets/icons/default/64/135-toy-train.png
    // Size: 3087
    static constexpr uint8_t toy_train[] = {
        #include "raw/icons/toy_train.inc.h"
    };

    // File: assets/icons/default/64/136-sailing-boat.png
    // Size: 2196
    static constexpr uint8_t sailing_boat[] = {
        #include "raw/icons/sailing_boat.inc.h"
    };

    // File: assets/icons/default/64/137-fire-truck.png
    // Size: 2859
    static constexpr uint8_t fire_truck[] = {
        #include "raw/icons/fire_truck.inc.h"
    };

    // File: assets/icons/default/64/138-bulldozer.png
    // Size: 2545
    static constexpr uint8_t bulldozer[] = {
        #include "raw/icons/bulldozer.inc.h"
    };

    // File: assets/icons/default/64/139-orca.png
    // Size: 3183
    static constexpr uint8_t orca[] = {
        #include "raw/icons/orca.inc.h"
    };

    // File: assets/icons/default/64/140-pet.png
    // Size: 3075
    static constexpr uint8_t pet[] = {
        #include "raw/icons/pet.inc.h"
    };

    // File: assets/icons/default/64/141-pen-drive.png
    // Size: 1184
    static constexpr uint8_t pen_drive[] = {
        #include "raw/icons/pen_drive.inc.h"
    };

    // File: assets/icons/default/64/142-ping-pong.png
    // Size: 2979
    static constexpr uint8_t ping_pong[] = {
        #include "raw/icons/ping_pong.inc.h"
    };

    // File: assets/icons/default/64/143-snake-1.png
    // Size: 2574
    static constexpr uint8_t snake_1[] = {
        #include "raw/icons/snake_1.inc.h"
    };

    // File: assets/icons/default/64/144-board-game.png
    // Size: 1949
    static constexpr uint8_t board_game[] = {
        #include "raw/icons/board_game.inc.h"
    };

    // File: assets/icons/default/64/145-dices.png
    // Size: 2881
    static constexpr uint8_t dices[] = {
        #include "raw/icons/dices.inc.h"
    };

    // File: assets/icons/default/64/146-swords.png
    // Size: 3690
    static constexpr uint8_t swords[] = {
        #include "raw/icons/swords.inc.h"
    };

    // File: assets/icons/default/64/147-mosaic.png
    // Size: 1343
    static constexpr uint8_t mosaic[] = {
        #include "raw/icons/mosaic.inc.h"
    };

    // File: assets/icons/default/64/148-clock.png
    // Size: 4080
    static constexpr uint8_t clock[] = {
        #include "raw/icons/clock.inc.h"
    };

    // File: assets/icons/default/64/149-alien.png
    // Size: 2125
    static constexpr uint8_t alien[] = {
        #include "raw/icons/alien.inc.h"
    };

    // File: assets/icons/default/64/150-alien-1.png
    // Size: 3045
    static constexpr uint8_t alien_1[] = {
        #include "raw/icons/alien_1.inc.h"
    };

    // File: assets/icons/default/64/151-alien-2.png
    // Size: 3371
    static constexpr uint8_t alien_2[] = {
        #include "raw/icons/alien_2.inc.h"
    };

    // File: assets/icons/default/64/152-space.png
    // Size: 2552
    static constexpr uint8_t space[] = {
        #include "raw/icons/space.inc.h"
    };

    // File: assets/icons/default/64/153-tetris.png
    // Size: 667
    static constexpr uint8_t tetris[] = {
        #include "raw/icons/tetris.inc.h"
    };

    // File: assets/icons/default/64/154-car-light.png
    // Size: 1794
    static constexpr uint8_t car_light[] = {
        #include "raw/icons/car_light.inc.h"
    };

    // File: assets/icons/default/64/155-arcade.png
    // Size: 1967
    static constexpr uint8_t arcade[] = {
        #include "raw/icons/arcade.inc.h"
    };

    // File: assets/icons/default/64/156-like.png
    // Size: 1576
    static constexpr uint8_t like[] = {
        #include "raw/icons/like.inc.h"
    };

    // File: assets/icons/default/64/157-ghost.png
    // Size: 1057
    static constexpr uint8_t ghost[] = {
        #include "raw/icons/ghost.inc.h"
    };

    // File: assets/icons/default/64/158-multimedia.png
    // Size: 3526
    static constexpr uint8_t multimedia[] = {
        #include "raw/icons/multimedia.inc.h"
    };

    // File: assets/icons/default/64/159-mouse.png
    // Size: 2245
    static constexpr uint8_t mouse[] = {
        #include "raw/icons/mouse.inc.h"
    };

    // File: assets/icons/default/64/160-pig.png
    // Size: 2371
    static constexpr uint8_t pig[] = {
        #include "raw/icons/pig.inc.h"
    };

    // File: assets/icons/default/64/161-mushroom.png
    // Size: 3058
    static constexpr uint8_t mushroom[] = {
        #include "raw/icons/mushroom.inc.h"
    };

    // File: assets/icons/default/64/162-duck.png
    // Size: 2803
    static constexpr uint8_t duck[] = {
        #include "raw/icons/duck.inc.h"
    };

    // File: assets/icons/default/64/163-fairy-2.png
    // Size: 3362
    static constexpr uint8_t fairy_2[] = {
        #include "raw/icons/fairy_2.inc.h"
    };

    // File: assets/icons/default/64/164-fairy-3.png
    // Size: 3594
    static constexpr uint8_t fairy_3[] = {
        #include "raw/icons/fairy_3.inc.h"
    };

    // File: assets/icons/default/64/165-detective.png
    // Size: 3577
    static constexpr uint8_t detective[] = {
        #include "raw/icons/detective.inc.h"
    };

    // File: assets/icons/default/64/166-dragon-boat.png
    // Size: 3238
    static constexpr uint8_t dragon_boat[] = {
        #include "raw/icons/dragon_boat.inc.h"
    };

    // File: assets/icons/default/64/167-witch.png
    // Size: 3566
    static constexpr uint8_t witch[] = {
        #include "raw/icons/witch.inc.h"
    };

    // File: assets/icons/default/64/168-wardrobe.png
    // Size: 1608
    static constexpr uint8_t wardrobe[] = {
        #include "raw/icons/wardrobe.inc.h"
    };

    // File: assets/icons/default/64/169-siren.png
    // Size: 1063
    static constexpr uint8_t siren[] = {
        #include "raw/icons/siren.inc.h"
    };

    // File: assets/icons/default/64/170-car-engine.png
    // Size: 4694
    static constexpr uint8_t car_engine[] = {
        #include "raw/icons/car_engine.inc.h"
    };

    // File: assets/icons/default/64/171-screenshot.png
    // Size: 2072
    static constexpr uint8_t screenshot[] = {
        #include "raw/icons/screenshot.inc.h"
    };

    // File: assets/icons/default/64/172-squirrel.png
    // Size: 3031
    static constexpr uint8_t squirrel[] = {
        #include "raw/icons/squirrel.inc.h"
    };

    // File: assets/icons/default/64/173-owl-1.png
    // Size: 3823
    static constexpr uint8_t owl_1[] = {
        #include "raw/icons/owl_1.inc.h"
    };

    // File: assets/icons/default/64/174-fish.png
    // Size: 2783
    static constexpr uint8_t fish[] = {
        #include "raw/icons/fish.inc.h"
    };

    // File: assets/icons/default/64/175-bird.png
    // Size: 2477
    static constexpr uint8_t bird[] = {
        #include "raw/icons/bird.inc.h"
    };

    // File: assets/icons/default/64/176-shiba.png
    // Size: 3530
    static constexpr uint8_t shiba[] = {
        #include "raw/icons/shiba.inc.h"
    };

    // File: assets/icons/default/64/177-bike.png
    // Size: 4640
    static constexpr uint8_t bike[] = {
        #include "raw/icons/bike.inc.h"
    };

    // File: assets/icons/default/64/178-buggy.png
    // Size: 3641
    static constexpr uint8_t buggy[] = {
        #include "raw/icons/buggy.inc.h"
    };

    // File: assets/icons/default/64/179-bicycle.png
    // Size: 3369
    static constexpr uint8_t bicycle[] = {
        #include "raw/icons/bicycle.inc.h"
    };

    // File: assets/icons/default/64/180-wooden-box.png
    // Size: 3195
    static constexpr uint8_t wooden_box[] = {
        #include "raw/icons/wooden_box.inc.h"
    };

    // File: assets/icons/default/64/181-boy.png
    // Size: 3508
    static constexpr uint8_t boy[] = {
        #include "raw/icons/boy.inc.h"
    };

    // File: assets/icons/default/64/182-wall.png
    // Size: 485
    static constexpr uint8_t wall[] = {
        #include "raw/icons/wall.inc.h"
    };

    // File: assets/icons/default/64/183-wall-1.png
    // Size: 607
    static constexpr uint8_t wall_1[] = {
        #include "raw/icons/wall_1.inc.h"
    };

    // File: assets/icons/default/64/184-woman.png
    // Size: 3877
    static constexpr uint8_t woman[] = {
        #include "raw/icons/woman.inc.h"
    };

    // File: assets/icons/default/64/185-girl.png
    // Size: 4017
    static constexpr uint8_t girl[] = {
        #include "raw/icons/girl.inc.h"
    };

    // File: assets/icons/default/64/186-hourglass.png
    // Size: 2158
    static constexpr uint8_t hourglass[] = {
        #include "raw/icons/hourglass.inc.h"
    };

    // File: assets/icons/default/64/187-gps.png
    // Size: 1402
    static constexpr uint8_t gps[] = {
        #include "raw/icons/gps.inc.h"
    };

    // File: assets/icons/default/64/188-gps-1.png
    // Size: 1507
    static constexpr uint8_t gps_1[] = {
        #include "raw/icons/gps_1.inc.h"
    };

    // File: assets/icons/default/64/189-music-note.png
    // Size: 2091
    static constexpr uint8_t music_note[] = {
        #include "raw/icons/music_note.inc.h"
    };

    // File: assets/icons/default/64/190-music-1.png
    // Size: 3152
    static constexpr uint8_t music_1[] = {
        #include "raw/icons/music_1.inc.h"
    };

    // File: assets/icons/default/64/191-red-panda.png
    // Size: 3693
    static constexpr uint8_t red_panda[] = {
        #include "raw/icons/red_panda.inc.h"
    };

    // File: assets/icons/default/64/192-red-panda-1.png
    // Size: 5156
    static constexpr uint8_t red_panda_1[] = {
        #include "raw/icons/red_panda_1.inc.h"
    };

    // File: assets/icons/default/64/193-animal.png
    // Size: 5182
    static constexpr uint8_t animal[] = {
        #include "raw/icons/animal.inc.h"
    };

    // File: assets/icons/default/64/194-animal-1.png
    // Size: 5279
    static constexpr uint8_t animal_1[] = {
        #include "raw/icons/animal_1.inc.h"
    };

    // File: assets/icons/default/64/195-animal-2.png
    // Size: 5377
    static constexpr uint8_t animal_2[] = {
        #include "raw/icons/animal_2.inc.h"
    };

    // File: assets/icons/default/64/196-animal-3.png
    // Size: 5076
    static constexpr uint8_t animal_3[] = {
        #include "raw/icons/animal_3.inc.h"
    };

    // File: assets/icons/default/64/197-animal-4.png
    // Size: 4958
    static constexpr uint8_t animal_4[] = {
        #include "raw/icons/animal_4.inc.h"
    };

    // File: assets/icons/default/64/198-owl-2.png
    // Size: 1915
    static constexpr uint8_t owl_2[] = {
        #include "raw/icons/owl_2.inc.h"
    };

    // File: assets/icons/default/64/199-animal-5.png
    // Size: 4931
    static constexpr uint8_t animal_5[] = {
        #include "raw/icons/animal_5.inc.h"
    };

    // File: assets/icons/default/64/200-calendar.png
    // Size: 2142
    static constexpr uint8_t calendar[] = {
        #include "raw/icons/calendar.inc.h"
    };

    // File: assets/icons/default/64/201-calendar-1.png
    // Size: 2302
    static constexpr uint8_t calendar_1[] = {
        #include "raw/icons/calendar_1.inc.h"
    };

    // File: assets/icons/default/64/202-chat.png
    // Size: 2658
    static constexpr uint8_t chat[] = {
        #include "raw/icons/chat.inc.h"
    };

    // File: assets/icons/default/64/203-chat-1.png
    // Size: 1115
    static constexpr uint8_t chat_1[] = {
        #include "raw/icons/chat_1.inc.h"
    };

    // File: assets/icons/default/64/204-medal.png
    // Size: 2513
    static constexpr uint8_t medal[] = {
        #include "raw/icons/medal.inc.h"
    };

    // File: assets/icons/default/64/205-star.png
    // Size: 2379
    static constexpr uint8_t star[] = {
        #include "raw/icons/star.inc.h"
    };

    // File: assets/icons/default/64/206-money-bag.png
    // Size: 2500
    static constexpr uint8_t money_bag[] = {
        #include "raw/icons/money_bag.inc.h"
    };

    // File: assets/icons/default/64/207-diamond.png
    // Size: 1983
    static constexpr uint8_t diamond[] = {
        #include "raw/icons/diamond.inc.h"
    };

    // File: assets/icons/default/64/208-diamond-1.png
    // Size: 1747
    static constexpr uint8_t diamond_1[] = {
        #include "raw/icons/diamond_1.inc.h"
    };

    // File: assets/icons/default/64/209-diamond-2.png
    // Size: 1872
    static constexpr uint8_t diamond_2[] = {
        #include "raw/icons/diamond_2.inc.h"
    };

    // File: assets/icons/default/64/210-costume.png
    // Size: 4248
    static constexpr uint8_t costume[] = {
        #include "raw/icons/costume.inc.h"
    };

    // File: assets/icons/default/64/211-play.png
    // Size: 1752
    static constexpr uint8_t play[] = {
        #include "raw/icons/play.inc.h"
    };

    // File: assets/icons/default/64/212-pause.png
    // Size: 2488
    static constexpr uint8_t pause[] = {
        #include "raw/icons/pause.inc.h"
    };

    // File: assets/icons/default/64/213-folder.png
    // Size: 2621
    static constexpr uint8_t folder[] = {
        #include "raw/icons/folder.inc.h"
    };

    // File: assets/icons/default/64/214-notes.png
    // Size: 2624
    static constexpr uint8_t notes[] = {
        #include "raw/icons/notes.inc.h"
    };

    // File: assets/icons/default/64/215-notebook.png
    // Size: 2636
    static constexpr uint8_t notebook[] = {
        #include "raw/icons/notebook.inc.h"
    };

} // namespace rckid::assets::icons_default_64
