#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: icons
namespace rckid::assets::icons{

    // File: 001-game-controller.png
    // Size: 3058
    static constexpr uint8_t game_controller[] = {
        #include "raw/icons/001-game-controller.png.h"
    };

    // File: 002-rc-car.png
    // Size: 2955
    static constexpr uint8_t rc_car[] = {
        #include "raw/icons/002-rc-car.png.h"
    };

    // File: 003-music.png
    // Size: 2532
    static constexpr uint8_t music[] = {
        #include "raw/icons/003-music.png.h"
    };

    // File: 004-flashlight.png
    // Size: 2323
    static constexpr uint8_t flashlight[] = {
        #include "raw/icons/004-flashlight.png.h"
    };

    // File: 005-film-slate.png
    // Size: 2563
    static constexpr uint8_t film_slate[] = {
        #include "raw/icons/005-film-slate.png.h"
    };

    // File: 006-baby-crib.png
    // Size: 3068
    static constexpr uint8_t baby_crib[] = {
        #include "raw/icons/006-baby-crib.png.h"
    };

    // File: 007-baby-monitor.png
    // Size: 2168
    static constexpr uint8_t baby_monitor[] = {
        #include "raw/icons/007-baby-monitor.png.h"
    };

    // File: 008-unicorn.png
    // Size: 5834
    static constexpr uint8_t unicorn[] = {
        #include "raw/icons/008-unicorn.png.h"
    };

    // File: 009-brightness.png
    // Size: 1908
    static constexpr uint8_t brightness[] = {
        #include "raw/icons/009-brightness.png.h"
    };

    // File: 010-high-volume.png
    // Size: 2396
    static constexpr uint8_t high_volume[] = {
        #include "raw/icons/010-high-volume.png.h"
    };

    // File: 011-power-off.png
    // Size: 3139
    static constexpr uint8_t power_off[] = {
        #include "raw/icons/011-power-off.png.h"
    };

    // File: 012-airplane-mode.png
    // Size: 1592
    static constexpr uint8_t airplane_mode[] = {
        #include "raw/icons/012-airplane-mode.png.h"
    };

    // File: 013-settings.png
    // Size: 2825
    static constexpr uint8_t settings[] = {
        #include "raw/icons/013-settings.png.h"
    };

    // File: 014-info.png
    // Size: 1707
    static constexpr uint8_t info[] = {
        #include "raw/icons/014-info.png.h"
    };

    // File: 015-alarm-clock.png
    // Size: 4855
    static constexpr uint8_t alarm_clock[] = {
        #include "raw/icons/015-alarm-clock.png.h"
    };

    // File: 016-wifi.png
    // Size: 2244
    static constexpr uint8_t wifi[] = {
        #include "raw/icons/016-wifi.png.h"
    };

    // File: 017-signal.png
    // Size: 3456
    static constexpr uint8_t signal[] = {
        #include "raw/icons/017-signal.png.h"
    };

    // File: 018-cancel.png
    // Size: 2359
    static constexpr uint8_t cancel[] = {
        #include "raw/icons/018-cancel.png.h"
    };

    // File: 019-sad.png
    // Size: 1699
    static constexpr uint8_t sad[] = {
        #include "raw/icons/019-sad.png.h"
    };

    // File: 020-poo.png
    // Size: 2396
    static constexpr uint8_t poo[] = {
        #include "raw/icons/020-poo.png.h"
    };

    // File: 021-birthday-cake.png
    // Size: 1876
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons/021-birthday-cake.png.h"
    };

    // File: 022-presents.png
    // Size: 3299
    static constexpr uint8_t presents[] = {
        #include "raw/icons/022-presents.png.h"
    };

    // File: 023-easter.png
    // Size: 3725
    static constexpr uint8_t easter[] = {
        #include "raw/icons/023-easter.png.h"
    };

    // File: 024-santa-hat.png
    // Size: 2516
    static constexpr uint8_t santa_hat[] = {
        #include "raw/icons/024-santa-hat.png.h"
    };

    // File: 025-heart.png
    // Size: 1981
    static constexpr uint8_t heart[] = {
        #include "raw/icons/025-heart.png.h"
    };

    // File: 026-magic-wand.png
    // Size: 2836
    static constexpr uint8_t magic_wand[] = {
        #include "raw/icons/026-magic-wand.png.h"
    };

    // File: 027-fairy.png
    // Size: 3027
    static constexpr uint8_t fairy[] = {
        #include "raw/icons/027-fairy.png.h"
    };

    // File: 028-unicorn-1.png
    // Size: 3341
    static constexpr uint8_t unicorn_1[] = {
        #include "raw/icons/028-unicorn-1.png.h"
    };

    // File: 029-book.png
    // Size: 3735
    static constexpr uint8_t book[] = {
        #include "raw/icons/029-book.png.h"
    };

    // File: 030-delivery-truck.png
    // Size: 1967
    static constexpr uint8_t delivery_truck[] = {
        #include "raw/icons/030-delivery-truck.png.h"
    };

    // File: 031-garbage-car.png
    // Size: 2613
    static constexpr uint8_t garbage_car[] = {
        #include "raw/icons/031-garbage-car.png.h"
    };

    // File: 032-hawaiian.png
    // Size: 3525
    static constexpr uint8_t hawaiian[] = {
        #include "raw/icons/032-hawaiian.png.h"
    };

    // File: 033-rabbit.png
    // Size: 3009
    static constexpr uint8_t rabbit[] = {
        #include "raw/icons/033-rabbit.png.h"
    };

    // File: 034-truck.png
    // Size: 1856
    static constexpr uint8_t truck[] = {
        #include "raw/icons/034-truck.png.h"
    };

    // File: 035-crab.png
    // Size: 3412
    static constexpr uint8_t crab[] = {
        #include "raw/icons/035-crab.png.h"
    };

    // File: 036-alpine-forget-me-not.png
    // Size: 4871
    static constexpr uint8_t alpine_forget_me_not[] = {
        #include "raw/icons/036-alpine-forget-me-not.png.h"
    };

    // File: 037-cat.png
    // Size: 2935
    static constexpr uint8_t cat[] = {
        #include "raw/icons/037-cat.png.h"
    };

    // File: 038-tamagochi.png
    // Size: 3159
    static constexpr uint8_t tamagochi[] = {
        #include "raw/icons/038-tamagochi.png.h"
    };

    // File: 039-walrus.png
    // Size: 2565
    static constexpr uint8_t walrus[] = {
        #include "raw/icons/039-walrus.png.h"
    };

    // File: 040-pea.png
    // Size: 3376
    static constexpr uint8_t pea[] = {
        #include "raw/icons/040-pea.png.h"
    };

    // File: 041-pine-tree.png
    // Size: 2074
    static constexpr uint8_t pine_tree[] = {
        #include "raw/icons/041-pine-tree.png.h"
    };

    // File: 042-water-gun.png
    // Size: 2201
    static constexpr uint8_t water_gun[] = {
        #include "raw/icons/042-water-gun.png.h"
    };

    // File: 043-ladybug.png
    // Size: 3519
    static constexpr uint8_t ladybug[] = {
        #include "raw/icons/043-ladybug.png.h"
    };

    // File: 044-mint-marigold.png
    // Size: 3626
    static constexpr uint8_t mint_marigold[] = {
        #include "raw/icons/044-mint-marigold.png.h"
    };

    // File: 045-candy.png
    // Size: 2998
    static constexpr uint8_t candy[] = {
        #include "raw/icons/045-candy.png.h"
    };

    // File: 046-windmill.png
    // Size: 1957
    static constexpr uint8_t windmill[] = {
        #include "raw/icons/046-windmill.png.h"
    };

    // File: 047-hedgehog.png
    // Size: 2944
    static constexpr uint8_t hedgehog[] = {
        #include "raw/icons/047-hedgehog.png.h"
    };

    // File: 048-freesia.png
    // Size: 4067
    static constexpr uint8_t freesia[] = {
        #include "raw/icons/048-freesia.png.h"
    };

    // File: 049-fruits.png
    // Size: 5099
    static constexpr uint8_t fruits[] = {
        #include "raw/icons/049-fruits.png.h"
    };

    // File: 050-rocking-horse.png
    // Size: 2441
    static constexpr uint8_t rocking_horse[] = {
        #include "raw/icons/050-rocking-horse.png.h"
    };

    // File: 051-cat-1.png
    // Size: 4116
    static constexpr uint8_t cat_1[] = {
        #include "raw/icons/051-cat-1.png.h"
    };

    // File: 052-geranium.png
    // Size: 4190
    static constexpr uint8_t geranium[] = {
        #include "raw/icons/052-geranium.png.h"
    };

    // File: 053-sunlight.png
    // Size: 3940
    static constexpr uint8_t sunlight[] = {
        #include "raw/icons/053-sunlight.png.h"
    };

    // File: 054-sword.png
    // Size: 2203
    static constexpr uint8_t sword[] = {
        #include "raw/icons/054-sword.png.h"
    };

    // File: 055-elephant.png
    // Size: 2739
    static constexpr uint8_t elephant[] = {
        #include "raw/icons/055-elephant.png.h"
    };

    // File: 056-lotus-flower.png
    // Size: 3862
    static constexpr uint8_t lotus_flower[] = {
        #include "raw/icons/056-lotus-flower.png.h"
    };

    // File: 057-trees.png
    // Size: 5030
    static constexpr uint8_t trees[] = {
        #include "raw/icons/057-trees.png.h"
    };

    // File: 058-sand-castle.png
    // Size: 1709
    static constexpr uint8_t sand_castle[] = {
        #include "raw/icons/058-sand-castle.png.h"
    };

    // File: 059-lama.png
    // Size: 2391
    static constexpr uint8_t lama[] = {
        #include "raw/icons/059-lama.png.h"
    };

    // File: 060-chive-blossoms.png
    // Size: 3985
    static constexpr uint8_t chive_blossoms[] = {
        #include "raw/icons/060-chive-blossoms.png.h"
    };

    // File: 061-rain.png
    // Size: 4737
    static constexpr uint8_t rain[] = {
        #include "raw/icons/061-rain.png.h"
    };

    // File: 062-blocks.png
    // Size: 778
    static constexpr uint8_t blocks[] = {
        #include "raw/icons/062-blocks.png.h"
    };

    // File: 063-hippo.png
    // Size: 2896
    static constexpr uint8_t hippo[] = {
        #include "raw/icons/063-hippo.png.h"
    };

    // File: 064-bouvardia.png
    // Size: 4734
    static constexpr uint8_t bouvardia[] = {
        #include "raw/icons/064-bouvardia.png.h"
    };

    // File: 065-greenhouse.png
    // Size: 5884
    static constexpr uint8_t greenhouse[] = {
        #include "raw/icons/065-greenhouse.png.h"
    };

    // File: 066-frog.png
    // Size: 2800
    static constexpr uint8_t frog[] = {
        #include "raw/icons/066-frog.png.h"
    };

    // File: 067-pineappleweed.png
    // Size: 3543
    static constexpr uint8_t pineappleweed[] = {
        #include "raw/icons/067-pineappleweed.png.h"
    };

    // File: 068-plant.png
    // Size: 4647
    static constexpr uint8_t plant[] = {
        #include "raw/icons/068-plant.png.h"
    };

    // File: 069-parrot.png
    // Size: 1632
    static constexpr uint8_t parrot[] = {
        #include "raw/icons/069-parrot.png.h"
    };

    // File: 070-bird-of-paradise.png
    // Size: 3553
    static constexpr uint8_t bird_of_paradise[] = {
        #include "raw/icons/070-bird-of-paradise.png.h"
    };

    // File: 071-beehive.png
    // Size: 4891
    static constexpr uint8_t beehive[] = {
        #include "raw/icons/071-beehive.png.h"
    };

    // File: 072-turtle.png
    // Size: 3263
    static constexpr uint8_t turtle[] = {
        #include "raw/icons/072-turtle.png.h"
    };

    // File: 073-aster.png
    // Size: 4839
    static constexpr uint8_t aster[] = {
        #include "raw/icons/073-aster.png.h"
    };

    // File: 074-watering-can.png
    // Size: 4239
    static constexpr uint8_t watering_can[] = {
        #include "raw/icons/074-watering-can.png.h"
    };

    // File: 075-rabbit-1.png
    // Size: 2886
    static constexpr uint8_t rabbit_1[] = {
        #include "raw/icons/075-rabbit-1.png.h"
    };

    // File: 076-snowdrop.png
    // Size: 3834
    static constexpr uint8_t snowdrop[] = {
        #include "raw/icons/076-snowdrop.png.h"
    };

    // File: 077-carrots.png
    // Size: 4431
    static constexpr uint8_t carrots[] = {
        #include "raw/icons/077-carrots.png.h"
    };

    // File: 078-penguin.png
    // Size: 2972
    static constexpr uint8_t penguin[] = {
        #include "raw/icons/078-penguin.png.h"
    };

    // File: 079-borage.png
    // Size: 3991
    static constexpr uint8_t borage[] = {
        #include "raw/icons/079-borage.png.h"
    };

    // File: 080-flower.png
    // Size: 6530
    static constexpr uint8_t flower[] = {
        #include "raw/icons/080-flower.png.h"
    };

    // File: 081-owl.png
    // Size: 3317
    static constexpr uint8_t owl[] = {
        #include "raw/icons/081-owl.png.h"
    };

    // File: 082-gladiolus.png
    // Size: 3448
    static constexpr uint8_t gladiolus[] = {
        #include "raw/icons/082-gladiolus.png.h"
    };

    // File: 083-bee.png
    // Size: 2313
    static constexpr uint8_t bee[] = {
        #include "raw/icons/083-bee.png.h"
    };

    // File: 084-tiger-lily.png
    // Size: 4221
    static constexpr uint8_t tiger_lily[] = {
        #include "raw/icons/084-tiger-lily.png.h"
    };

    // File: 085-rhino.png
    // Size: 2888
    static constexpr uint8_t rhino[] = {
        #include "raw/icons/085-rhino.png.h"
    };

    // File: 086-bluebell.png
    // Size: 3637
    static constexpr uint8_t bluebell[] = {
        #include "raw/icons/086-bluebell.png.h"
    };

    // File: 087-snake.png
    // Size: 2440
    static constexpr uint8_t snake[] = {
        #include "raw/icons/087-snake.png.h"
    };

    // File: 088-lavender.png
    // Size: 3988
    static constexpr uint8_t lavender[] = {
        #include "raw/icons/088-lavender.png.h"
    };

    // File: 089-bullfinch.png
    // Size: 3001
    static constexpr uint8_t bullfinch[] = {
        #include "raw/icons/089-bullfinch.png.h"
    };

    // File: 090-peony.png
    // Size: 4387
    static constexpr uint8_t peony[] = {
        #include "raw/icons/090-peony.png.h"
    };

    // File: 091-fox.png
    // Size: 2809
    static constexpr uint8_t fox[] = {
        #include "raw/icons/091-fox.png.h"
    };

    // File: 092-orchid.png
    // Size: 3447
    static constexpr uint8_t orchid[] = {
        #include "raw/icons/092-orchid.png.h"
    };

    // File: 093-dog.png
    // Size: 3076
    static constexpr uint8_t dog[] = {
        #include "raw/icons/093-dog.png.h"
    };

    // File: 094-chicken.png
    // Size: 2272
    static constexpr uint8_t chicken[] = {
        #include "raw/icons/094-chicken.png.h"
    };

    // File: 095-panda.png
    // Size: 3385
    static constexpr uint8_t panda[] = {
        #include "raw/icons/095-panda.png.h"
    };

    // File: 096-gorilla.png
    // Size: 3443
    static constexpr uint8_t gorilla[] = {
        #include "raw/icons/096-gorilla.png.h"
    };

    // File: 097-squid.png
    // Size: 2910
    static constexpr uint8_t squid[] = {
        #include "raw/icons/097-squid.png.h"
    };

    // File: 098-chameleon.png
    // Size: 3142
    static constexpr uint8_t chameleon[] = {
        #include "raw/icons/098-chameleon.png.h"
    };

    // File: 099-cow.png
    // Size: 3161
    static constexpr uint8_t cow[] = {
        #include "raw/icons/099-cow.png.h"
    };

    // File: 100-buffalo.png
    // Size: 2898
    static constexpr uint8_t buffalo[] = {
        #include "raw/icons/100-buffalo.png.h"
    };

    // File: 101-horse.png
    // Size: 3046
    static constexpr uint8_t horse[] = {
        #include "raw/icons/101-horse.png.h"
    };

    // File: 102-platypus.png
    // Size: 2457
    static constexpr uint8_t platypus[] = {
        #include "raw/icons/102-platypus.png.h"
    };

    // File: 103-sloth.png
    // Size: 3379
    static constexpr uint8_t sloth[] = {
        #include "raw/icons/103-sloth.png.h"
    };

    // File: 104-stingray.png
    // Size: 2356
    static constexpr uint8_t stingray[] = {
        #include "raw/icons/104-stingray.png.h"
    };

    // File: 105-zebra.png
    // Size: 4152
    static constexpr uint8_t zebra[] = {
        #include "raw/icons/105-zebra.png.h"
    };

    // File: 106-crocodile.png
    // Size: 3171
    static constexpr uint8_t crocodile[] = {
        #include "raw/icons/106-crocodile.png.h"
    };

    // File: 107-shark.png
    // Size: 2511
    static constexpr uint8_t shark[] = {
        #include "raw/icons/107-shark.png.h"
    };

    // File: 108-camel.png
    // Size: 2907
    static constexpr uint8_t camel[] = {
        #include "raw/icons/108-camel.png.h"
    };

    // File: 109-butterfly.png
    // Size: 2372
    static constexpr uint8_t butterfly[] = {
        #include "raw/icons/109-butterfly.png.h"
    };

    // File: 110-boar.png
    // Size: 3021
    static constexpr uint8_t boar[] = {
        #include "raw/icons/110-boar.png.h"
    };

    // File: 111-deer.png
    // Size: 2919
    static constexpr uint8_t deer[] = {
        #include "raw/icons/111-deer.png.h"
    };

    // File: 112-whale.png
    // Size: 2423
    static constexpr uint8_t whale[] = {
        #include "raw/icons/112-whale.png.h"
    };

    // File: 113-spider.png
    // Size: 3832
    static constexpr uint8_t spider[] = {
        #include "raw/icons/113-spider.png.h"
    };

    // File: 114-bat.png
    // Size: 3133
    static constexpr uint8_t bat[] = {
        #include "raw/icons/114-bat.png.h"
    };

    // File: 115-beaver.png
    // Size: 3128
    static constexpr uint8_t beaver[] = {
        #include "raw/icons/115-beaver.png.h"
    };

    // File: 116-giraffe.png
    // Size: 2752
    static constexpr uint8_t giraffe[] = {
        #include "raw/icons/116-giraffe.png.h"
    };

    // File: 117-microphone.png
    // Size: 3240
    static constexpr uint8_t microphone[] = {
        #include "raw/icons/117-microphone.png.h"
    };

    // File: 118-applications.png
    // Size: 2046
    static constexpr uint8_t applications[] = {
        #include "raw/icons/118-applications.png.h"
    };

    // File: 119-gameboy.png
    // Size: 1560
    static constexpr uint8_t gameboy[] = {
        #include "raw/icons/119-gameboy.png.h"
    };

    // File: 120-sand-clock.png
    // Size: 1853
    static constexpr uint8_t sand_clock[] = {
        #include "raw/icons/120-sand-clock.png.h"
    };

    // File: 121-chase.png
    // Size: 4002
    static constexpr uint8_t chase[] = {
        #include "raw/icons/121-chase.png.h"
    };

    // File: 122-ambulance.png
    // Size: 2049
    static constexpr uint8_t ambulance[] = {
        #include "raw/icons/122-ambulance.png.h"
    };

    // File: 123-fairy-tale.png
    // Size: 3654
    static constexpr uint8_t fairy_tale[] = {
        #include "raw/icons/123-fairy-tale.png.h"
    };

    // File: 124-fairy-1.png
    // Size: 2906
    static constexpr uint8_t fairy_1[] = {
        #include "raw/icons/124-fairy-1.png.h"
    };

    // File: 125-fairy-tale-1.png
    // Size: 3865
    static constexpr uint8_t fairy_tale_1[] = {
        #include "raw/icons/125-fairy-tale-1.png.h"
    };

    // File: 126-cinderella-carriage.png
    // Size: 4254
    static constexpr uint8_t cinderella_carriage[] = {
        #include "raw/icons/126-cinderella-carriage.png.h"
    };

    // File: 127-cinderella-shoe.png
    // Size: 2824
    static constexpr uint8_t cinderella_shoe[] = {
        #include "raw/icons/127-cinderella-shoe.png.h"
    };

    // File: 128-forklift.png
    // Size: 2932
    static constexpr uint8_t forklift[] = {
        #include "raw/icons/128-forklift.png.h"
    };

    // File: 129-lynx.png
    // Size: 5020
    static constexpr uint8_t lynx[] = {
        #include "raw/icons/129-lynx.png.h"
    };

    // File: 130-steering-wheel.png
    // Size: 3948
    static constexpr uint8_t steering_wheel[] = {
        #include "raw/icons/130-steering-wheel.png.h"
    };

    // File: 131-paint-palette.png
    // Size: 3267
    static constexpr uint8_t paint_palette[] = {
        #include "raw/icons/131-paint-palette.png.h"
    };

    // File: 132-horn.png
    // Size: 1428
    static constexpr uint8_t horn[] = {
        #include "raw/icons/132-horn.png.h"
    };

    // File: 133-frog-1.png
    // Size: 2973
    static constexpr uint8_t frog_1[] = {
        #include "raw/icons/133-frog-1.png.h"
    };

    // File: 134-digger.png
    // Size: 2327
    static constexpr uint8_t digger[] = {
        #include "raw/icons/134-digger.png.h"
    };

    // File: 135-toy-train.png
    // Size: 3087
    static constexpr uint8_t toy_train[] = {
        #include "raw/icons/135-toy-train.png.h"
    };

    // File: 136-sailing-boat.png
    // Size: 2196
    static constexpr uint8_t sailing_boat[] = {
        #include "raw/icons/136-sailing-boat.png.h"
    };

    // File: 137-fire-truck.png
    // Size: 2859
    static constexpr uint8_t fire_truck[] = {
        #include "raw/icons/137-fire-truck.png.h"
    };

    // File: 138-bulldozer.png
    // Size: 2545
    static constexpr uint8_t bulldozer[] = {
        #include "raw/icons/138-bulldozer.png.h"
    };

    // File: 139-orca.png
    // Size: 3183
    static constexpr uint8_t orca[] = {
        #include "raw/icons/139-orca.png.h"
    };

    // File: 140-pet.png
    // Size: 3075
    static constexpr uint8_t pet[] = {
        #include "raw/icons/140-pet.png.h"
    };
} // namespace rckid::assets::icons
