#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: icons24
namespace rckid::assets::icons24{

    // File: 152-space.png
    // Size: 1107
    static constexpr uint8_t space[] = {
        #include "raw/icons24/152-space.png.h"
    };
} // namespace rckid::assets::icons24
