#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: icons16
namespace rckid::assets::icons16{

    // File: 149-alien.png
    // Size: 710
    static constexpr uint8_t alien[] = {
        #include "raw/icons16/149-alien.png.h"
    };

    // File: 150-alien-1.png
    // Size: 722
    static constexpr uint8_t alien_1[] = {
        #include "raw/icons16/150-alien-1.png.h"
    };

    // File: 151-alien-2.png
    // Size: 750
    static constexpr uint8_t alien_2[] = {
        #include "raw/icons16/151-alien-2.png.h"
    };
} // namespace rckid::assets::icons16
