#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  assets/images rckid/assets/images.h --raw-path raw/images
 */

namespace rckid::assets {

    // File: assets/images/star.png
    // Size: 736
    static constexpr uint8_t star[] = {
        #include "raw/images/star.inc.h"
    };

    // File: assets/images/logo16.png
    // Size: 3186
    static constexpr uint8_t logo16[] = {
        #include "raw/images/logo16.inc.h"
    };

    // File: assets/images/logo256.png
    // Size: 7268
    static constexpr uint8_t logo256[] = {
        #include "raw/images/logo256.inc.h"
    };

} // namespace rckid::assets
