#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  assets/images rckid/assets/images.h --raw-path raw/images
 */

namespace rckid::assets {

    // File: assets/images/logo16.png
    // Size: 3421
    static constexpr uint8_t logo16[] = {
        #include "raw/images/logo16.inc.h"
    };

    // File: assets/images/background16.png
    // Size: 19762
    static constexpr uint8_t background16[] = {
        #include "raw/images/background16.inc.h"
    };

} // namespace rckid::assets
