#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: images
namespace rckid::assets::images{

    // File: logo16.png
    // Size: 3186
    static constexpr uint8_t logo16[] = {
        #include "raw/images/logo16.png.h"
    };

    // File: logo256.png
    // Size: 7268
    static constexpr uint8_t logo256[] = {
        #include "raw/images/logo256.png.h"
    };
} // namespace rckid::assets::images
