#pragma once

// DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY generate-assets

#include "../rckid.h"

// Folder: tests
namespace rckid::assets::tests{

    // File: raw_audio_44100_16_signed.raw
    // Size: 3847680
    static constexpr uint8_t raw_audio_44100_16_signed[] = {
        #include "raw/tests/raw_audio_44100_16_signed.raw.h"
    };
} // namespace rckid::assets::tests
