#include <cstdlib>
#include <iostream>
#include <fstream>

int main(int argc, char * argv[]) {


    // 5 bit channel == 0..31 
    // 6 bit channel == 0..63

    unsigned RED[] = {0, 4, 9, 13, 18, 22, 27, 31}; // 3 to 5
    unsigned GREEN[] = {0, 9, 18, 27, 36, 45, 54, 63}; // 3 to 6
    unsigned BLUE[] = {0, 10, 21, 31}; // 2 to 5

    std::ofstream f{argv[1]};
    std::cout << "Saving to " << argv[1] << std::endl;
    f << "#pragma once" << std::endl << std::endl;
    f << "/* This is autogenerated quick palette translation table from RGB 332 to RGB565." << std::endl;
    f << "   Do not edit this file manually, use the generator instead." << std::endl;
    f << " */" << std::endl << std::endl;
    f << "#include \"rckid/rckid.h\"" << std::endl << std::endl;
    f << "namespace rckid {" << std::endl;
    f << "    static constexpr uint16_t Palette_332_to_565[] = {" << std::endl;
    for (unsigned i = 0; i < 256; ++i) {
        unsigned r = (i >> 5) & 7;
        unsigned g = (i >> 3) & 7;
        unsigned b = i & 3;
        unsigned result = (RED[r] << 11) + (GREEN[g] << 5) + BLUE[b];
        f << "        " << result << ", // r: " << r << ", g: " << g << ", b: " << b << " (" << i << ")" << std::endl;
    }
    f << "    };" << std::endl;
    f << "}" << std::endl;
    return EXIT_SUCCESS;
}