#pragma once

/* This is autogenerated assets file, do not edit manually.
   source folder:      assets/rckid
   destination folder: librckid/assets
 */

#include <cstdint>

namespace rckid::assets {

    namespace icons {
        constexpr uint8_t game_controller[] = {
            #include "icons/001-game-controller.png.inc"
        }; // 3058 bytes
        constexpr uint8_t rc_car[] = {
            #include "icons/002-rc-car.png.inc"
        }; // 2955 bytes
        constexpr uint8_t music[] = {
            #include "icons/003-music.png.inc"
        }; // 2532 bytes
        constexpr uint8_t flashlight[] = {
            #include "icons/004-flashlight.png.inc"
        }; // 2323 bytes
        constexpr uint8_t film_slate[] = {
            #include "icons/005-film-slate.png.inc"
        }; // 2563 bytes
        constexpr uint8_t baby_crib[] = {
            #include "icons/006-baby-crib.png.inc"
        }; // 3068 bytes
        constexpr uint8_t baby_monitor[] = {
            #include "icons/007-baby-monitor.png.inc"
        }; // 2168 bytes
        constexpr uint8_t unicorn[] = {
            #include "icons/008-unicorn.png.inc"
        }; // 5834 bytes
        constexpr uint8_t brightness[] = {
            #include "icons/009-brightness.png.inc"
        }; // 1908 bytes
        constexpr uint8_t high_volume[] = {
            #include "icons/010-high-volume.png.inc"
        }; // 2396 bytes
        constexpr uint8_t power_off[] = {
            #include "icons/011-power-off.png.inc"
        }; // 3139 bytes
        constexpr uint8_t airplane_mode[] = {
            #include "icons/012-airplane-mode.png.inc"
        }; // 1592 bytes
        constexpr uint8_t settings[] = {
            #include "icons/013-settings.png.inc"
        }; // 2825 bytes
        constexpr uint8_t info[] = {
            #include "icons/014-info.png.inc"
        }; // 1707 bytes
        constexpr uint8_t alarm_clock[] = {
            #include "icons/015-alarm-clock.png.inc"
        }; // 4855 bytes
        constexpr uint8_t wifi[] = {
            #include "icons/016-wifi.png.inc"
        }; // 2244 bytes
        constexpr uint8_t signal[] = {
            #include "icons/017-signal.png.inc"
        }; // 3456 bytes
        constexpr uint8_t cancel[] = {
            #include "icons/018-cancel.png.inc"
        }; // 2359 bytes
        constexpr uint8_t sad[] = {
            #include "icons/019-sad.png.inc"
        }; // 1699 bytes
        constexpr uint8_t poo[] = {
            #include "icons/020-poo.png.inc"
        }; // 2396 bytes
        constexpr uint8_t birthday_cake[] = {
            #include "icons/021-birthday-cake.png.inc"
        }; // 1876 bytes
        constexpr uint8_t presents[] = {
            #include "icons/022-presents.png.inc"
        }; // 3299 bytes
        constexpr uint8_t easter[] = {
            #include "icons/023-easter.png.inc"
        }; // 3725 bytes
        constexpr uint8_t santa_hat[] = {
            #include "icons/024-santa-hat.png.inc"
        }; // 2516 bytes
        constexpr uint8_t heart[] = {
            #include "icons/025-heart.png.inc"
        }; // 1981 bytes
        constexpr uint8_t magic_wand[] = {
            #include "icons/026-magic-wand.png.inc"
        }; // 2836 bytes
        constexpr uint8_t fairy[] = {
            #include "icons/027-fairy.png.inc"
        }; // 3027 bytes
        constexpr uint8_t unicorn_1[] = {
            #include "icons/028-unicorn-1.png.inc"
        }; // 3341 bytes
        constexpr uint8_t book[] = {
            #include "icons/029-book.png.inc"
        }; // 3735 bytes
        constexpr uint8_t delivery_truck[] = {
            #include "icons/030-delivery-truck.png.inc"
        }; // 1967 bytes
        constexpr uint8_t garbage_car[] = {
            #include "icons/031-garbage-car.png.inc"
        }; // 2613 bytes
        constexpr uint8_t hawaiian[] = {
            #include "icons/032-hawaiian.png.inc"
        }; // 3525 bytes
        constexpr uint8_t rabbit[] = {
            #include "icons/033-rabbit.png.inc"
        }; // 3009 bytes
        constexpr uint8_t truck[] = {
            #include "icons/034-truck.png.inc"
        }; // 1856 bytes
        constexpr uint8_t crab[] = {
            #include "icons/035-crab.png.inc"
        }; // 3412 bytes
        constexpr uint8_t alpine_forget_me_not[] = {
            #include "icons/036-alpine-forget-me-not.png.inc"
        }; // 4871 bytes
        constexpr uint8_t cat[] = {
            #include "icons/037-cat.png.inc"
        }; // 2935 bytes
        constexpr uint8_t tamagochi[] = {
            #include "icons/038-tamagochi.png.inc"
        }; // 3159 bytes
        constexpr uint8_t walrus[] = {
            #include "icons/039-walrus.png.inc"
        }; // 2565 bytes
        constexpr uint8_t pea[] = {
            #include "icons/040-pea.png.inc"
        }; // 3376 bytes
        constexpr uint8_t pine_tree[] = {
            #include "icons/041-pine-tree.png.inc"
        }; // 2074 bytes
        constexpr uint8_t water_gun[] = {
            #include "icons/042-water-gun.png.inc"
        }; // 2201 bytes
        constexpr uint8_t ladybug[] = {
            #include "icons/043-ladybug.png.inc"
        }; // 3519 bytes
        constexpr uint8_t mint_marigold[] = {
            #include "icons/044-mint-marigold.png.inc"
        }; // 3626 bytes
        constexpr uint8_t candy[] = {
            #include "icons/045-candy.png.inc"
        }; // 2998 bytes
        constexpr uint8_t windmill[] = {
            #include "icons/046-windmill.png.inc"
        }; // 1957 bytes
        constexpr uint8_t hedgehog[] = {
            #include "icons/047-hedgehog.png.inc"
        }; // 2944 bytes
        constexpr uint8_t freesia[] = {
            #include "icons/048-freesia.png.inc"
        }; // 4067 bytes
        constexpr uint8_t fruits[] = {
            #include "icons/049-fruits.png.inc"
        }; // 5099 bytes
        constexpr uint8_t rocking_horse[] = {
            #include "icons/050-rocking-horse.png.inc"
        }; // 2441 bytes
        constexpr uint8_t cat_1[] = {
            #include "icons/051-cat-1.png.inc"
        }; // 4116 bytes
        constexpr uint8_t geranium[] = {
            #include "icons/052-geranium.png.inc"
        }; // 4190 bytes
        constexpr uint8_t sunlight[] = {
            #include "icons/053-sunlight.png.inc"
        }; // 3940 bytes
        constexpr uint8_t sword[] = {
            #include "icons/054-sword.png.inc"
        }; // 2203 bytes
        constexpr uint8_t elephant[] = {
            #include "icons/055-elephant.png.inc"
        }; // 2739 bytes
        constexpr uint8_t lotus_flower[] = {
            #include "icons/056-lotus-flower.png.inc"
        }; // 3862 bytes
        constexpr uint8_t trees[] = {
            #include "icons/057-trees.png.inc"
        }; // 5030 bytes
        constexpr uint8_t sand_castle[] = {
            #include "icons/058-sand-castle.png.inc"
        }; // 1709 bytes
        constexpr uint8_t lama[] = {
            #include "icons/059-lama.png.inc"
        }; // 2391 bytes
        constexpr uint8_t chive_blossoms[] = {
            #include "icons/060-chive-blossoms.png.inc"
        }; // 3985 bytes
        constexpr uint8_t rain[] = {
            #include "icons/061-rain.png.inc"
        }; // 4737 bytes
        constexpr uint8_t blocks[] = {
            #include "icons/062-blocks.png.inc"
        }; // 778 bytes
        constexpr uint8_t hippo[] = {
            #include "icons/063-hippo.png.inc"
        }; // 2896 bytes
        constexpr uint8_t bouvardia[] = {
            #include "icons/064-bouvardia.png.inc"
        }; // 4734 bytes
        constexpr uint8_t greenhouse[] = {
            #include "icons/065-greenhouse.png.inc"
        }; // 5884 bytes
        constexpr uint8_t frog[] = {
            #include "icons/066-frog.png.inc"
        }; // 2800 bytes
        constexpr uint8_t pineappleweed[] = {
            #include "icons/067-pineappleweed.png.inc"
        }; // 3543 bytes
        constexpr uint8_t plant[] = {
            #include "icons/068-plant.png.inc"
        }; // 4647 bytes
        constexpr uint8_t parrot[] = {
            #include "icons/069-parrot.png.inc"
        }; // 1632 bytes
        constexpr uint8_t bird_of_paradise[] = {
            #include "icons/070-bird-of-paradise.png.inc"
        }; // 3553 bytes
        constexpr uint8_t beehive[] = {
            #include "icons/071-beehive.png.inc"
        }; // 4891 bytes
        constexpr uint8_t turtle[] = {
            #include "icons/072-turtle.png.inc"
        }; // 3263 bytes
        constexpr uint8_t aster[] = {
            #include "icons/073-aster.png.inc"
        }; // 4839 bytes
        constexpr uint8_t watering_can[] = {
            #include "icons/074-watering-can.png.inc"
        }; // 4239 bytes
        constexpr uint8_t rabbit_1[] = {
            #include "icons/075-rabbit-1.png.inc"
        }; // 2886 bytes
        constexpr uint8_t snowdrop[] = {
            #include "icons/076-snowdrop.png.inc"
        }; // 3834 bytes
        constexpr uint8_t carrots[] = {
            #include "icons/077-carrots.png.inc"
        }; // 4431 bytes
        constexpr uint8_t penguin[] = {
            #include "icons/078-penguin.png.inc"
        }; // 2972 bytes
        constexpr uint8_t borage[] = {
            #include "icons/079-borage.png.inc"
        }; // 3991 bytes
        constexpr uint8_t flower[] = {
            #include "icons/080-flower.png.inc"
        }; // 6530 bytes
        constexpr uint8_t owl[] = {
            #include "icons/081-owl.png.inc"
        }; // 3317 bytes
        constexpr uint8_t gladiolus[] = {
            #include "icons/082-gladiolus.png.inc"
        }; // 3448 bytes
        constexpr uint8_t bee[] = {
            #include "icons/083-bee.png.inc"
        }; // 2313 bytes
        constexpr uint8_t tiger_lily[] = {
            #include "icons/084-tiger-lily.png.inc"
        }; // 4221 bytes
        constexpr uint8_t rhino[] = {
            #include "icons/085-rhino.png.inc"
        }; // 2888 bytes
        constexpr uint8_t bluebell[] = {
            #include "icons/086-bluebell.png.inc"
        }; // 3637 bytes
        constexpr uint8_t snake[] = {
            #include "icons/087-snake.png.inc"
        }; // 2440 bytes
        constexpr uint8_t lavender[] = {
            #include "icons/088-lavender.png.inc"
        }; // 3988 bytes
        constexpr uint8_t bullfinch[] = {
            #include "icons/089-bullfinch.png.inc"
        }; // 3001 bytes
        constexpr uint8_t peony[] = {
            #include "icons/090-peony.png.inc"
        }; // 4387 bytes
        constexpr uint8_t fox[] = {
            #include "icons/091-fox.png.inc"
        }; // 2809 bytes
        constexpr uint8_t orchid[] = {
            #include "icons/092-orchid.png.inc"
        }; // 3447 bytes
        constexpr uint8_t dog[] = {
            #include "icons/093-dog.png.inc"
        }; // 3076 bytes
        constexpr uint8_t chicken[] = {
            #include "icons/094-chicken.png.inc"
        }; // 2272 bytes
        constexpr uint8_t panda[] = {
            #include "icons/095-panda.png.inc"
        }; // 3385 bytes
        constexpr uint8_t gorilla[] = {
            #include "icons/096-gorilla.png.inc"
        }; // 3443 bytes
        constexpr uint8_t squid[] = {
            #include "icons/097-squid.png.inc"
        }; // 2910 bytes
        constexpr uint8_t chameleon[] = {
            #include "icons/098-chameleon.png.inc"
        }; // 3142 bytes
        constexpr uint8_t cow[] = {
            #include "icons/099-cow.png.inc"
        }; // 3161 bytes
        constexpr uint8_t buffalo[] = {
            #include "icons/100-buffalo.png.inc"
        }; // 2898 bytes
        constexpr uint8_t horse[] = {
            #include "icons/101-horse.png.inc"
        }; // 3046 bytes
        constexpr uint8_t platypus[] = {
            #include "icons/102-platypus.png.inc"
        }; // 2457 bytes
        constexpr uint8_t sloth[] = {
            #include "icons/103-sloth.png.inc"
        }; // 3379 bytes
        constexpr uint8_t stingray[] = {
            #include "icons/104-stingray.png.inc"
        }; // 2356 bytes
        constexpr uint8_t zebra[] = {
            #include "icons/105-zebra.png.inc"
        }; // 4152 bytes
        constexpr uint8_t crocodile[] = {
            #include "icons/106-crocodile.png.inc"
        }; // 3171 bytes
        constexpr uint8_t shark[] = {
            #include "icons/107-shark.png.inc"
        }; // 2511 bytes
        constexpr uint8_t camel[] = {
            #include "icons/108-camel.png.inc"
        }; // 2907 bytes
        constexpr uint8_t butterfly[] = {
            #include "icons/109-butterfly.png.inc"
        }; // 2372 bytes
        constexpr uint8_t boar[] = {
            #include "icons/110-boar.png.inc"
        }; // 3021 bytes
        constexpr uint8_t deer[] = {
            #include "icons/111-deer.png.inc"
        }; // 2919 bytes
        constexpr uint8_t whale[] = {
            #include "icons/112-whale.png.inc"
        }; // 2423 bytes
        constexpr uint8_t spider[] = {
            #include "icons/113-spider.png.inc"
        }; // 3832 bytes
        constexpr uint8_t bat[] = {
            #include "icons/114-bat.png.inc"
        }; // 3133 bytes
        constexpr uint8_t beaver[] = {
            #include "icons/115-beaver.png.inc"
        }; // 3128 bytes
        constexpr uint8_t giraffe[] = {
            #include "icons/116-giraffe.png.inc"
        }; // 2752 bytes
        constexpr uint8_t microphone[] = {
            #include "icons/117-microphone.png.inc"
        }; // 3240 bytes
        constexpr uint8_t applications[] = {
            #include "icons/118-applications.png.inc"
        }; // 2046 bytes
        constexpr uint8_t gameboy[] = {
            #include "icons/119-gameboy.png.inc"
        }; // 1560 bytes
        constexpr uint8_t sand_clock[] = {
            #include "icons/120-sand-clock.png.inc"
        }; // 1853 bytes
        constexpr uint8_t chase[] = {
            #include "icons/121-chase.png.inc"
        }; // 4002 bytes
        constexpr uint8_t ambulance[] = {
            #include "icons/122-ambulance.png.inc"
        }; // 2049 bytes
        constexpr uint8_t fairy_tale[] = {
            #include "icons/123-fairy-tale.png.inc"
        }; // 3654 bytes
        constexpr uint8_t fairy_1[] = {
            #include "icons/124-fairy-1.png.inc"
        }; // 2906 bytes
        constexpr uint8_t fairy_tale_1[] = {
            #include "icons/125-fairy-tale-1.png.inc"
        }; // 3865 bytes
        constexpr uint8_t cinderella_carriage[] = {
            #include "icons/126-cinderella-carriage.png.inc"
        }; // 4254 bytes
        constexpr uint8_t cinderella_shoe[] = {
            #include "icons/127-cinderella-shoe.png.inc"
        }; // 2824 bytes
        constexpr uint8_t forklift[] = {
            #include "icons/128-forklift.png.inc"
        }; // 2932 bytes
        constexpr uint8_t lynx[] = {
            #include "icons/129-lynx.png.inc"
        }; // 5020 bytes
        constexpr uint8_t steering_wheel[] = {
            #include "icons/130-steering-wheel.png.inc"
        }; // 3948 bytes
        constexpr uint8_t paint_palette[] = {
            #include "icons/131-paint-palette.png.inc"
        }; // 3267 bytes
        constexpr uint8_t horn[] = {
            #include "icons/132-horn.png.inc"
        }; // 1428 bytes
        constexpr uint8_t frog_1[] = {
            #include "icons/133-frog-1.png.inc"
        }; // 2973 bytes
        constexpr uint8_t digger[] = {
            #include "icons/134-digger.png.inc"
        }; // 2327 bytes
        constexpr uint8_t toy_train[] = {
            #include "icons/135-toy-train.png.inc"
        }; // 3087 bytes
        constexpr uint8_t sailing_boat[] = {
            #include "icons/136-sailing-boat.png.inc"
        }; // 2196 bytes
        constexpr uint8_t fire_truck[] = {
            #include "icons/137-fire-truck.png.inc"
        }; // 2859 bytes
        constexpr uint8_t bulldozer[] = {
            #include "icons/138-bulldozer.png.inc"
        }; // 2545 bytes
        constexpr uint8_t orca[] = {
            #include "icons/139-orca.png.inc"
        }; // 3183 bytes
        constexpr uint8_t pet[] = {
            #include "icons/140-pet.png.inc"
        }; // 3075 bytes
    } // 439707 for namespace icons

    namespace images {
        constexpr uint8_t logo_black_16[] = {
            #include "images/logo_black_16.png.inc"
        }; // 3186 bytes
        constexpr uint8_t logo_black_256[] = {
            #include "images/logo_black_256.png.inc"
        }; // 7268 bytes
        constexpr uint8_t url_qr[] = {
            #include "images/url_qr.png.inc"
        }; // 369 bytes
    } // 10823 for namespace images
} // 450530 for namespace rckid::assets
