#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  icons/icons_16 /home/peta/devel/rckid/sdk/include/assets/icons_16.h --raw-path raw/icons_16 --namespace rckid::assets::icons_16
 */

namespace rckid::assets::icons_16 {

    // File: icons/icons_16/088-number-one.png
    // Size: 630
    static constexpr uint8_t number_one[] = {
        #include "raw/icons_16/number_one.inc.h"
    };

    // File: icons/icons_16/046-bookmark.png
    // Size: 452
    static constexpr uint8_t bookmark[] = {
        #include "raw/icons_16/bookmark.inc.h"
    };

    // File: icons/icons_16/058-email.png
    // Size: 343
    static constexpr uint8_t email[] = {
        #include "raw/icons_16/email.inc.h"
    };

    // File: icons/icons_16/052-play-button.png
    // Size: 543
    static constexpr uint8_t play_button[] = {
        #include "raw/icons_16/play_button.inc.h"
    };

    // File: icons/icons_16/089-letter-a.png
    // Size: 745
    static constexpr uint8_t letter_a[] = {
        #include "raw/icons_16/letter_a.inc.h"
    };

    // File: icons/icons_16/090-text.png
    // Size: 208
    static constexpr uint8_t text[] = {
        #include "raw/icons_16/text.inc.h"
    };

    // File: icons/icons_16/056-phone.png
    // Size: 653
    static constexpr uint8_t phone[] = {
        #include "raw/icons_16/phone.inc.h"
    };

    // File: icons/icons_16/085-backspace.png
    // Size: 335
    static constexpr uint8_t backspace[] = {
        #include "raw/icons_16/backspace.inc.h"
    };

    // File: icons/icons_16/087-right-arrow.png
    // Size: 496
    static constexpr uint8_t right_arrow[] = {
        #include "raw/icons_16/right_arrow.inc.h"
    };

    // File: icons/icons_16/086-back-arrow.png
    // Size: 471
    static constexpr uint8_t back_arrow[] = {
        #include "raw/icons_16/back_arrow.inc.h"
    };

    // File: icons/icons_16/065-light.png
    // Size: 735
    static constexpr uint8_t light[] = {
        #include "raw/icons_16/light.inc.h"
    };

    // File: icons/icons_16/016-birthday-cake.png
    // Size: 606
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons_16/birthday_cake.inc.h"
    };

    // File: icons/icons_16/057-house.png
    // Size: 831
    static constexpr uint8_t house[] = {
        #include "raw/icons_16/house.inc.h"
    };

    // File: icons/icons_16/044-picture.png
    // Size: 807
    static constexpr uint8_t picture[] = {
        #include "raw/icons_16/picture.inc.h"
    };

} // namespace rckid::assets::icons_16
