#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  icons/icons_24 /home/peta/devel/rckid/sdk/include/assets/icons_24.h --raw-path raw/icons_24 --namespace rckid::assets::icons_24
 */

namespace rckid::assets::icons_24 {

    // File: icons/icons_24/046-bookmark.png
    // Size: 613
    static constexpr uint8_t bookmark[] = {
        #include "raw/icons_24/bookmark.inc.h"
    };

    // File: icons/icons_24/058-email.png
    // Size: 487
    static constexpr uint8_t email[] = {
        #include "raw/icons_24/email.inc.h"
    };

    // File: icons/icons_24/060-exchange.png
    // Size: 949
    static constexpr uint8_t exchange[] = {
        #include "raw/icons_24/exchange.inc.h"
    };

    // File: icons/icons_24/056-phone.png
    // Size: 930
    static constexpr uint8_t phone[] = {
        #include "raw/icons_24/phone.inc.h"
    };

    // File: icons/icons_24/059-shuffle.png
    // Size: 1005
    static constexpr uint8_t shuffle[] = {
        #include "raw/icons_24/shuffle.inc.h"
    };

    // File: icons/icons_24/016-birthday-cake.png
    // Size: 824
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons_24/birthday_cake.inc.h"
    };

    // File: icons/icons_24/057-house.png
    // Size: 1265
    static constexpr uint8_t house[] = {
        #include "raw/icons_24/house.inc.h"
    };

} // namespace rckid::assets::icons_24
