#pragma once
/* DO NOT EDIT THIS FILE, IT HAS BEEN AUTOGENERATED BY THE FOLLOWING COMMAND: 
   binary-folder  icons/icons_24 /home/petam/devel/rckid/sdk/include/assets/icons_24.h --raw-path raw/icons_24 --namespace rckid::assets::icons_24
 */

namespace rckid::assets::icons_24 {

    // File: icons/icons_24/105-diagram.png
    // Size: 1289
    static constexpr uint8_t diagram[] = {
        #include "raw/icons_24/diagram.inc.h"
    };

    // File: icons/icons_24/095-switch-on.png
    // Size: 848
    static constexpr uint8_t switch_on[] = {
        #include "raw/icons_24/switch_on.inc.h"
    };

    // File: icons/icons_24/046-bookmark.png
    // Size: 613
    static constexpr uint8_t bookmark[] = {
        #include "raw/icons_24/bookmark.inc.h"
    };

    // File: icons/icons_24/057-house.png
    // Size: 1265
    static constexpr uint8_t house[] = {
        #include "raw/icons_24/house.inc.h"
    };

    // File: icons/icons_24/038-money-bag.png
    // Size: 901
    static constexpr uint8_t money_bag[] = {
        #include "raw/icons_24/money_bag.inc.h"
    };

    // File: icons/icons_24/059-shuffle.png
    // Size: 1005
    static constexpr uint8_t shuffle[] = {
        #include "raw/icons_24/shuffle.inc.h"
    };

    // File: icons/icons_24/060-exchange.png
    // Size: 949
    static constexpr uint8_t exchange[] = {
        #include "raw/icons_24/exchange.inc.h"
    };

    // File: icons/icons_24/058-email.png
    // Size: 487
    static constexpr uint8_t email[] = {
        #include "raw/icons_24/email.inc.h"
    };

    // File: icons/icons_24/096-switch-off.png
    // Size: 712
    static constexpr uint8_t switch_off[] = {
        #include "raw/icons_24/switch_off.inc.h"
    };

    // File: icons/icons_24/104-arrows.png
    // Size: 671
    static constexpr uint8_t arrows[] = {
        #include "raw/icons_24/arrows.inc.h"
    };

    // File: icons/icons_24/056-phone.png
    // Size: 930
    static constexpr uint8_t phone[] = {
        #include "raw/icons_24/phone.inc.h"
    };

    // File: icons/icons_24/097-checked.png
    // Size: 1272
    static constexpr uint8_t checked[] = {
        #include "raw/icons_24/checked.inc.h"
    };

    // File: icons/icons_24/016-birthday-cake.png
    // Size: 824
    static constexpr uint8_t birthday_cake[] = {
        #include "raw/icons_24/birthday_cake.inc.h"
    };

    // File: icons/icons_24/071-family.png
    // Size: 1881
    static constexpr uint8_t family[] = {
        #include "raw/icons_24/family.inc.h"
    };

} // namespace rckid::assets::icons_24
